examples/pytorch/llm/scripts/qwen_7b/qlora_ddp/infer.sh, examples/pytorch/llm/scripts/qwen_7b/qlora_ddp/sft.sh, examples/pytorch/llm/scripts/qwen_7b_chat/qlora/sft.sh, examples/pytorch/llm/scripts/qwen_7b_chat/qlora_ddp/sft.sh, examples/pytorch/llm/scripts/qwen_agent/qlora_ddp/sft.sh, examples/pytorch/llm/scripts/qwen_vl/qlora_ddp/infer.sh, examples/pytorch/llm/scripts/qwen_vl/qlora_ddp/sft.sh, examples/pytorch/llm/scripts/qwen_vl_chat/qlora/sft.sh, examples/pytorch/llm/scripts/qwen_vl_chat/qlora_ddp/sft.sh, examples/pytorch/llm/src/llm_infer.py, examples/pytorch/llm/src/llm_sft.py, examples/pytorch/llm/src/utils/__init__.py, examples/pytorch/llm/src/utils/dataset.py, examples/pytorch/llm/src/utils/model.py, examples/pytorch/llm/src/utils/preprocess.py, examples/pytorch/llm/src/utils/trainer_patch.py, examples/pytorch/llm/src/utils/utils.py, swift/tuners/prompt.py
1. add copyright
2. fix template bug
=> fix template bug2

README.md, README_CN.md, examples/pytorch/llm/README.md, examples/pytorch/llm/README_CN.md, examples/pytorch/llm/scripts/openbuddy-llama2-70b/qlora/infer.sh, examples/pytorch/llm/scripts/openbuddy-llama2-70b/qlora/sft.sh, examples/pytorch/llm/src/utils/model.py, examples/pytorch/llm/src/utils/preprocess.py, swift/trainers/mixin.py, swift/trainers/utils.py, swift/utils/__init__.py, swift/utils/torch_utils.py
1. update openbuddy llama2 70b
=> Add openbuddy llama2

README.md, README_CN.md, examples/pytorch/llm/README.md, examples/pytorch/llm/README_CN.md, examples/pytorch/llm/scripts/internlm_7b_chat/lora_ddp/infer.sh, examples/pytorch/llm/scripts/internlm_7b_chat/lora_ddp/sft.sh, examples/pytorch/llm/scripts/qwen_vl/lora_ddp/infer.sh, examples/pytorch/llm/scripts/qwen_vl/lora_ddp/sft.sh, examples/pytorch/llm/src/utils/dataset.py, examples/pytorch/llm/src/utils/model.py, examples/pytorch/llm/src/utils/preprocess.py
1. add internlm
2. update readme
=> Add internlm

swift/tuners/lora.py
diffusers  will call `query = attn.to_q(hidden_states, scale=scale)`
which including a useless scale parameter which swift will not use
=> Fix bug: LoRA not work with diffusers>0.20.0

swift/tuners/base.py, swift/tuners/neftune.py, swift/tuners/rome/rome.py, swift/tuners/utils.py, tests/tuners/test_neft.py
call save_pretrained:
1. (with lora, neftune): save adapter subfolders, neftune will save only config file
2. (no lora, only neftune): base_model.save_pretrained will be called, if no save_pretrained function, state_dict will be called and saved
=> Fix the saving behaviour of modules without state dict

swift/llm/utils/argument.py, swift/trainers/trainers.py
benchmark: test_basic
Memory: 19027MiB -> 18101MiB
Speed: 4.41s/it -> 4.31s/it
Best Eval Loss: 0.03413723 -> 0.03413723 (step 5)
=> update compute loss

examples/pytorch/llm/scripts/qwen_72b_chat/torchacc/full_fsdp_sft.sh, examples/pytorch/llm/scripts/qwen_72b_chat/torchacc/lora_fsdp_sft.sh, swift/llm/accelerator.py, swift/llm/sft.py, swift/llm/tuner.py, swift/llm/utils/__init__.py, swift/llm/utils/argument.py, swift/llm/utils/model.py, swift/llm/utils/template.py, swift/llm/utils/utils.py, swift/torchacc_utils.py, swift/trainers/arguments.py, swift/trainers/mixin.py, swift/trainers/trainers.py, swift/trainers/utils.py, swift/utils/__init__.py, swift/utils/torch_utils.py
TorchAcc is a framework developed by Alibaba PAI to accelerate PyTorch model training, providing computational acceleration based on compilation optimization and distributed strategies such as FSDP and TP+SP. This PR uses TorchAcc to accelerate the training of Swift SFT LoRA and Full scenarios and provides examples of qwen-72b-chat. Users can enable TorchAcc acceleration by setting `export USE_TORCHACC=1`. Currently, this feature is still in the experimental stage and only available internally.
Test with 4*80G A100 on qwen-72b-chat lora with script: 
```sh examples/pytorch/llm/scripts/qwen_72b_chat/torchacc/lora_fsdp_sft.sh```
{"eval_loss": 0.35520425, "eval_acc": 0.87996558, "eval_runtime": 753.7452, "eval_samples_per_second": 0.362, "eval_steps_per_second": 0.004, "epoch": 1.0, …
=>  [TorchAcc][Experimental] Integrate TorchAcc.

swift/llm/utils/template.py
Fix the error caused by reading the file in CMYK format during the processing of multi-modal models.
FIX ISSUE: https://github.com/modelscope/swift/issues/677
=> fix multimodal model image_mode = 'CMYK' (fix issue#677)

docs/source/Multi-Modal/minicpm-v-2最佳实践.md, swift/llm/utils/model.py, swift/llm/utils/template.py
1. support minicpm-v-2
2. fix minicpm-v template when multi round
=> feat(model): support minicpm-v-2

swift/llm/utils/template.py
Fix training with loss_scale
```shell
TypeError: unsupported operand types for -:`NoneType` and `int`
```
This is because the wrong indent of the if case
=> Fix loss scale

.github/PULL_REQUEST_TEMPLATE.md, docs/source/LLM/命令行参数.md, docs/source_en/LLM/Command-line-parameters.md, swift/llm/utils/dataset.py
=> Fix custom dataset bug

swift/llm/sft.py, swift/llm/tuner.py, swift/llm/utils/argument.py, swift/llm/utils/template.py, swift/trainers/trainers.py
Hi! `Sequence Parallel` and `Dataset Packing` are supported with XTuner in this pull request.
Sequence Parallel makes it possible to train large models with long sequence length using less training resources (GPU memory, GPU number).
Packing Dataset into max length can provide a substantial training speed increase (more than 10 times).
```
git clone https://github.com/InternLM/xtuner.git
cd xtuner
pip install -e '.[all]'
```
(XTuner will release next version as soon as posible)
1. Set `sequence_parallel_size` in arguments to enable sequence parallel strategy.
```
python swift/cli/sft.py --sequence_parallel_size 4 ...
```
2. Set `pack_to_max_length` to `true` to enable dataset packing.
```
python swift/cli/sft.py --pack_to_max_length true ...
```
- Training 32k context length Llama3 8B …
=> [Feature] Support sequence parallel with XTuner

swift/llm/sft.py, swift/llm/tuner.py, swift/llm/utils/argument.py, swift/llm/utils/template.py, swift/trainers/trainers.py
This reverts commit fbf37a46946721b34626ef534d267c9be582e1ba.
Temporary revert, waiting for a later refactor to achieve matching code
=> Temporary revert code, waiting for refactor.

swift/llm/utils/model.py
FIX ISSUE: https://github.com/modelscope/swift/issues/837
device_map:
```sh
CUDA_VISIBLE_DEVICES=0,1 swift sft \
--model_type internlm-xcomposer2-7b-chat \
--dataset coco-mini-en \
CUDA_VISIBLE_DEVICES=0,1,2,3 swift sft \
--model_type internlm-xcomposer2-7b-chat \
--dataset coco-mini-en \
```
zero2:
```sh
CUDA_VISIBLE_DEVICES=0,1,2,3 NPROC_PER_NODE=4 swift sft \
--model_type internlm-xcomposer2-7b-chat \
--dataset coco-mini-en \
--deepspeed default-zero2
```
=> fix xcomposer device_map

docs/source/LLM/命令行参数.md, docs/source_en/LLM/Command-line-parameters.md, swift/llm/utils/argument.py, swift/llm/utils/dataset.py, swift/llm/utils/preprocess.py
1. dataset_info如果传入dict, 则进行deepcopy, 防止对传入数值产生影响.
2. swift infer中dataset_test_ratio的默认值改为None. 在是否load_dataset_config情况下使用不同的行为.
English:
1. If dataset_info is passed as a dict, perform a deepcopy to prevent affecting the passed values.
2. The default value of dataset_test_ratio in swift infer is changed to None, with different behavior depending on whether load_dataset_config is used or not.
=> fix dataset info deepcopy

swift/cli/main.py
Job executed on remote machine relies on the exit code of the command to determine if the job is successful or a failure. Currently, the swift cli always returns an exit code of 0, which leads to a situation where even if the training job actually fails, it is still considered successful at the job level.
before 
current PR branch test result:
=> fix swift cli exit code if subprocess is failed

swift/llm/utils/model.py, swift/llm/utils/utils.py
fix bug described in https://github.com/OpenGVLab/InternVL/issues/129
```
bitsandbytes/autograd/_functions.py", line 479, in backward
.mul_(state.SCB.unsqueeze(1).mul(1.0 / 127.0))
RuntimeError: The size of tensor a (92576) must match the size of tensor b (92553) at non-singleton dimension 0
```
=> fix Internvl-int8 sft bug

swift/trainers/mixin.py
cpu环境下 无cuda，但是调用了get_max_cuda_memory方法，导致报错
=> 修复cpu环境下 module 'torch._C' has no attribute '_cuda_resetPeakMemoryStats 的错误

docs/source/LLM/命令行参数.md, docs/source_en/LLM/Command-line-parameters.md, swift/llm/utils/argument.py
=> fix docs and a bug

swift/llm/dpo.py, swift/llm/orpo.py, swift/llm/sft.py, swift/llm/simpo.py, swift/trainers/callback.py
=> fix eval strategy compat

swift/aigc/utils/argument.py, swift/llm/utils/argument.py
NPU机器下训练，使用torch-npu结合torch会报无法找到nccl、ccl等相关错误信息，需要指定hccl，因此再此加入hccl选项，可在NPU上进行正常的训练
NPU机器训练测试通过
=> 在argument.py添加hccl参数，用于NPU环境下训练使用

.dev_scripts/dockerci.sh, swift/llm/infer.py, swift/llm/rlhf.py, swift/llm/sft.py, swift/trainers/kto_trainer.py
=> Fix device map in limited mem

swift/llm/utils/dataset.py, swift/llm/utils/preprocess.py
Dataset concatenation may raise following errors:
```text
_check_if_features_can_be_aligned
raise ValueError(
ValueError: The features can't be aligned because the key history of features {'system': Value(dtype='null', id=None), 'history': Sequence(feature=Sequence(feature=Value(dtype='string', id=None), length=-1, id=None), length=-1, id=None), 'query': Value(dtype='string', id=None), 'response': Value(dtype='string', id=None)} has unexpected type - Sequence(feature=Sequence(feature=Value(dtype='string', id=None), length=-1, id=None), length=-1, id=None) (expected either Sequence(feature=Value(dtype='null', id=None), length=-1, id=None) or Value("null").
```
This is because some dataset has empty values and None values, and another one has normal history values, so the arrow_dataset will …
=> Fix dataset concatenation

swift/llm/utils/template.py
The current `GLM4VTemplate` does not have a `data_collator` function, which results in calling the `data_collator` function of the base class `Template`:
```python
res = {
'input_ids': input_ids,
'attention_mask': attention_mask,
'labels': labels,
}
if loss_scale is not None:
res['loss_scale'] = loss_scale
return res
```
The `res` returned by the base class function does not include `images`, causing the training of `glm4v` to only train on pure text.
=> Fix glm4v dataloader

swift/llm/utils/dataset.py, swift/llm/utils/preprocess.py
=> Fix vqa dataset loading

docs/source/LLM/命令行参数.md, docs/source_en/LLM/Command-line-parameters.md, examples/pytorch/llm/scripts/torchacc/baichuan2_13b_chat/acc_lora_dp_sft.sh, examples/pytorch/llm/scripts/torchacc/baichuan2_13b_chat/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/baichuan2_13b_chat/swift_lora_sft.sh, examples/pytorch/llm/scripts/torchacc/chatglm3_6b/acc_lora_dp_sft.sh, examples/pytorch/llm/scripts/torchacc/chatglm3_6b/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/chatglm3_6b/swift_lora_sft.sh, examples/pytorch/llm/scripts/torchacc/llama2_13b_chat/acc_lora_dp_sft.sh, examples/pytorch/llm/scripts/torchacc/llama2_13b_chat/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/llama2_13b_chat/swift_lora_sft.sh, examples/pytorch/llm/scripts/torchacc/llama3_8b_instruct/acc_lora_dp_sft.sh, examples/pytorch/llm/scripts/torchacc/llama3_8b_instruct/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/llama3_8b_instruct/swift_lora_sft.sh, examples/pytorch/llm/scripts/torchacc/qwen1half_14b_chat/acc_lora_dp_sft.sh, examples/pytorch/llm/scripts/torchacc/qwen1half_14b_chat/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/qwen1half_14b_chat/swift_lora_sft.sh, examples/pytorch/llm/scripts/torchacc/qwen1half_32b_chat/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/qwen1half_32b_chat/swift_lora_sft.sh, examples/pytorch/llm/scripts/torchacc/qwen_72b_chat/acc_full_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/qwen_72b_chat/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/qwen_72b_chat/swift_lora_sft.sh, examples/pytorch/llm/scripts/torchacc/yi_34b_chat/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/yi_34b_chat/swift_lora_sft.sh, swift/llm/utils/argument.py, swift/trainers/trainers.py
llama3-8b
method | train_sample/s | train_sample/s after warmup
-- | -- | --
acc2.3 + 2ddp+acc_steps100 | 12.608 | 14.554
acc2.3 + 2ddp+acc_steps1 | 10.096 | 11.304
</article>
=> [TorchAcc] Add acc_steps arguments to speed up torchacc training

swift/tuners/mapping.py, swift/tuners/part.py, tests/tuners/test_swift_base.py
=> Add a tuner to train a part of the model

docs/source/Multi-Modal/cogvlm2最佳实践.md, docs/source/Multi-Modal/cogvlm最佳实践.md, docs/source/Multi-Modal/deepseek-vl最佳实践.md, docs/source/Multi-Modal/glm4v最佳实践.md, docs/source/Multi-Modal/index.md, docs/source/Multi-Modal/internlm-xcomposer2最佳实践.md, docs/source/Multi-Modal/internvl最佳实践.md, docs/source/Multi-Modal/llava最佳实践.md, docs/source/Multi-Modal/minicpm-v-2.5最佳实践.md, docs/source/Multi-Modal/minicpm-v-2最佳实践.md, docs/source/Multi-Modal/minicpm-v最佳实践.md, docs/source/Multi-Modal/mplug-owl2最佳实践.md, docs/source/Multi-Modal/phi3-vision最佳实践.md, docs/source/Multi-Modal/qwen-vl最佳实践.md, docs/source/Multi-Modal/yi-vl最佳实践.md, swift/llm/infer.py, swift/llm/utils/dataset.py, swift/llm/utils/media.py, swift/llm/utils/model.py, swift/llm/utils/preprocess.py, swift/llm/utils/template.py
1. 在所有的MLLM最佳实践中增加OCR测试, 并对所有多模态模型进行检查
2. fix dataset中的非split问题, 抛出错误, 而不是打印error log
3. template.py的代码优化
4. replace_tag等函数返回List[Context], pre_tokenize的位置放置在_simplify_context_list之前
5. fix qwen-audio bug
=> refactor multi-modal

examples/pytorch/llm/scripts/torchacc/baichuan2_13b_chat/swift_lora_sft.sh, examples/pytorch/llm/scripts/torchacc/chatglm3_6b/swift_lora_sft.sh, examples/pytorch/llm/scripts/torchacc/llama2_13b_chat/swift_lora_sft.sh, examples/pytorch/llm/scripts/torchacc/llama3_8b_instruct/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/llama3_8b_instruct/swift_lora_sft.sh, examples/pytorch/llm/scripts/torchacc/qwen1half_14b_chat/swift_lora_sft.sh, examples/pytorch/llm/scripts/torchacc/qwen1half_32b_chat/swift_lora_sft.sh, examples/pytorch/llm/scripts/torchacc/qwen_72b_chat/swift_lora_sft.sh, examples/pytorch/llm/scripts/torchacc/yi_34b_chat/swift_lora_sft.sh
=> [TorchAcc] Add USE_TORCH_XLA=0 flag for native swift scripts

swift/llm/infer.py, swift/llm/utils/argument.py, swift/llm/utils/preprocess.py, swift/llm/utils/utils.py, swift/llm/utils/vllm_utils.py, swift/trainers/mixin.py
=> refactor inference

swift/hub/api.py
(cherry picked from commit 16cc33c700e5eff3639eaf5ecbf9fb6b463b1cd9)
=> add push to hub tracker

requirements/llm.txt, swift/llm/eval.py, swift/llm/utils/dataset.py, swift/llm/utils/preprocess.py
1. 重构dataset, preprocess部分代码和逻辑 (注意：未对ListPreprocessor进行修改)
```python
from swift.llm import get_dataset
dataset = get_dataset('iic/ms_bench')[0]
"""
Map: 100%|███████████████████████████████████████████████| 317623/317623 [00:31<00:00, 10085.15 examples/s]
Filter: 100%|████████████████████████████████████████████| 317623/317623 [00:10<00:00, 30777.00 examples/s]
Map: 100%|████████████████████████████████████████████████| 316734/316734 [00:46<00:00, 6880.82 examples/s]
Map: 100%|█████████████████████████████████████████████████| 317623/317623 [00:31<00:00, 9993.46 examples/s]
Filter: 100%|█████████████████████████████████████████████| 317623/317623 [00:10<00:00, 31072.59 examples/s]
"""
```
=> update dataset preprocess

swift/llm/utils/template.py
=> fix template

docs/source/Multi-Modal/vLLM推理加速文档.md, docs/source_en/Multi-Modal/vllm-inference-acceleration.md
=> compat with vllm==0.5.1

docs/source/Multi-Modal/cogvlm2-video最佳实践.md, docs/source_en/Multi-Modal/cogvlm2-video-best-practice.md, swift/llm/utils/model.py
FIX: https://github.com/modelscope/swift/issues/1335
=> fix xcomposer2.5 device_map

examples/pytorch/llm/scripts/torchacc/llama3_70b_instruct/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/llama3_70b_instruct/swift_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/llama3_8b_instruct/swift_lora_sft.sh, swift/llm/accelerator.py, swift/trainers/mixin.py
1. Update torchacc accelerate API;
2. fix accuracy calculation;
3. add llama3-70b examples.
swift deepspeed zeros3: 2.029 samples/s
torchacc fsdp: 2.641 samples/s
=> [TorchAcc] update accelerate API and add llama3-70B

docs/source/Multi-Modal/minicpm-v-2.5最佳实践.md, swift/llm/utils/argument.py, swift/llm/utils/model.py
=> fix minicpm-v2.5 lora_target_modules

swift/llm/infer.py, swift/llm/utils/argument.py, swift/llm/utils/utils.py
1. Added a `result_dir` parameter to `InferArgument`. This allows for specification of a designated result directory, providing an alternative to using `ckpt_dir`.
2. Fixed a minor bug in the string formatting of `AssertionError`.
=> add result_dir paramerter to InferArgument & fix a minor bug

docs/source/AIGC/AnimateDiff微调推理文档.md, docs/source/LLM/Agent微调最佳实践.md, docs/source/LLM/DPO训练文档.md, docs/source/LLM/Grok训练和推理.md, docs/source/LLM/LLM量化文档.md, docs/source/LLM/命令行参数.md, docs/source_en/AIGC/AnimateDiff-train-infer.md, docs/source_en/LLM/Agent-fine-tuning-best-practice.md, docs/source_en/LLM/Command-line-parameters.md, docs/source_en/LLM/DPO.md, docs/source_en/LLM/Grok-1-best-practice.md, docs/source_en/LLM/LLM-quantization.md, requirements/framework.txt, swift/aigc/animatediff.py, swift/aigc/utils/argument.py, swift/cli/main.py, swift/cli/pt.py, swift/llm/__init__.py, swift/llm/export.py, swift/llm/megatron/argument.py, swift/llm/sft.py, swift/llm/tuner.py, swift/llm/utils/__init__.py, swift/llm/utils/argument.py, swift/llm/utils/template.py, swift/ui/llm_train/lora.py
1. megatron qwen2-72b-instruct
2. pt_main, PtArguments
3. remove optimum
4. fix qwen-vl-chat & lmdeploy (check_example)
=> Fix bugs 0801

swift/llm/utils/dataset.py
FIX: https://github.com/modelscope/swift/issues/1453
=> fix dataset copy

swift/llm/sft.py, swift/torchacc_utils.py
1. Update TorchAcc patch for transformers when it's version >=4.41.0;
2. Update `update_causal_mask` in llama patch.
=> [TorchAcc] Update patch for transformers>=4.41.0

examples/pytorch/llm/scripts/torchacc/baichuan2_13b_chat/acc_lora_dp_sft.sh, examples/pytorch/llm/scripts/torchacc/baichuan2_13b_chat/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/chatglm3_6b/acc_lora_dp_sft.sh, examples/pytorch/llm/scripts/torchacc/chatglm3_6b/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/llama2_13b_chat/acc_lora_dp_sft.sh, examples/pytorch/llm/scripts/torchacc/llama2_13b_chat/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/llama3_70b_instruct/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/llama3_8b_instruct/acc_lora_dp_sft.sh, examples/pytorch/llm/scripts/torchacc/llama3_8b_instruct/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/qwen1half_14b_chat/acc_lora_dp_sft.sh, examples/pytorch/llm/scripts/torchacc/qwen1half_14b_chat/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/qwen1half_32b_chat/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/qwen2_72b_chat/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/qwen2_7b_chat/acc_lora_dp_sft.sh, examples/pytorch/llm/scripts/torchacc/qwen2_7b_chat/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/qwen_72b_chat/acc_full_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/qwen_72b_chat/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/yi_34b_chat/acc_lora_fsdp_sft.sh, swift/trainers/trainers.py
Add `ta.mark_step()` when gradient_accumulation_steps > 1 to reduce memory usage.
Before this PR, Torchacc compiled for each gradient_accumulation_steps. After this PR, it will compile for each individual step. Thus, this change will reduce the graph size, leading to decreased memory usage.
=> [TorchAcc] fix: add mark_step when GA is greater than 1

examples/pytorch/llm/scripts/torchacc/llama3_70b_instruct/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/qwen2_72b_chat/acc_lora_fsdp_sft.sh, swift/torchacc_utils.py
Change default bucketing  strategy from uniform with 4 buckets to normal distribution with 8 buckets, and allow user to set buckets size through environment variable `TORCHACC_DATA_BUCKETS`
=> [TorchAcc] update data bucketing strategy

swift/llm/tuner.py, swift/tuners/__init__.py, swift/tuners/reft.py
=> fix imports

swift/llm/megatron/utils.py
When the environment variable `PAI_MEGATRON_PATCH_PATH` is set, the following error occurs: 
```
UnboundLocalError: local variable 'megatron_patch_path' referenced before assignment.
```
This error occurs because the variable `megatron_patch_path` is not declared in this context.
The change made was to assign the value of the environment variable `PAI_MEGATRON_PATCH_PATH` to `megatron_patch_path`.
=> fix megatron_patch_path

swift/llm/export.py
When exporting the Megatron model, the `get_model_tokenizer` function did not include the `model_id_or_path` parameter. 
This has now been improved by passing the `model_id_or_path parameter`, allowing the correct usage of local models in offline environments.
=> fix offline export

README.md, README_CN.md, swift/llm/deploy.py, swift/llm/utils/argument.py
=> fix dora deployment

docs/source/Multi-Modal/qwen2-vl最佳实践.md, docs/source_en/Multi-Modal/qwen2-vl-best-practice.md
=> update docs qwen2-vl

examples/pytorch/llm/scripts/torchacc/baichuan2_13b_chat/acc_lora_dp_sft.sh, examples/pytorch/llm/scripts/torchacc/baichuan2_13b_chat/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/chatglm3_6b/acc_lora_dp_sft.sh, examples/pytorch/llm/scripts/torchacc/chatglm3_6b/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/llama2_13b_chat/acc_lora_dp_sft.sh, examples/pytorch/llm/scripts/torchacc/llama2_13b_chat/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/llama3_70b_instruct/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/llama3_8b_instruct/acc_lora_dp_sft.sh, examples/pytorch/llm/scripts/torchacc/llama3_8b_instruct/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/qwen1half_14b_chat/acc_lora_dp_sft.sh, examples/pytorch/llm/scripts/torchacc/qwen1half_14b_chat/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/qwen1half_32b_chat/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/qwen2_72b_chat/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/qwen2_7b_chat/acc_lora_dp_sft.sh, examples/pytorch/llm/scripts/torchacc/qwen2_7b_chat/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/qwen_72b_chat/acc_full_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/qwen_72b_chat/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/yi_34b_chat/acc_lora_fsdp_sft.sh, swift/llm/accelerator.py, swift/llm/sft.py, swift/torchacc_utils.py, swift/trainers/trainers.py
1. remove mark_step() after compute_loss to speed up performance and reduce memory usage;
2. fix accelerate's clip_grad_norm_ for FSDP;
3. fix XLA_PERSISTENT_CACHE_PATH conflict in multi-processing case;
4. use flatten_parameters in full sft FSDP to better overlap communication and computation.
=> [TorchAcc] fix serveral bugs for torchacc FSDP.

swift/llm/data/dataset_info.json, swift/llm/sft.py, swift/llm/utils/argument.py, swift/trainers/arguments.py, swift/trainers/mixin.py, swift/trainers/push_to_ms.py, swift/trainers/trainers.py
=> Refactor push_to_hub

swift/trainers/push_to_ms.py
=> Fix push_to_hub when last-checkpoint

swift/torchacc_utils.py
use xm.save instead of torch.save when saving optimizer states and lr_scheduler
=> [TorchAcc] perf: use xm.save instead of torch.save

docs/source/Instruction/命令行参数.md, docs/source_en/Instruction/Command-line-parameters.md, swift/llm/utils/argument.py
FIX ISSUE: https://github.com/modelscope/ms-swift/issues/1943
=> fix do_sample

swift/llm/utils/lmdeploy_utils.py
`EngineGenerationConfig` is removed from lmdeploy and swift can't use `inference_lmdeploy` due to `importError`
https://github.com/InternLM/lmdeploy/pull/2375/files
https://github.com/InternLM/lmdeploy/issues/2435
```
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
from swift.llm import (
ModelType, get_lmdeploy_engine, get_default_template_type,
get_template, inference_lmdeploy, inference_stream_lmdeploy
)
model_type = ModelType.internvl2_2b
model_id_or_path = None
lmdeploy_engine = get_lmdeploy_engine(model_type, model_id_or_path=model_id_or_path)
template_type = get_default_template_type(model_type)
template = get_template(template_type, lmdeploy_engine.hf_tokenizer)
lmdeploy_engine.generation_config.max_new_tokens = 256
generation_info = {}
request_list = [{'query': '<image>描述图片', …
```
=> fix EngineGenerationConfig importError of lmdeploy

swift/llm/rlhf.py, swift/llm/sft.py, swift/llm/utils/argument.py, swift/llm/utils/template.py
=> fix RLHF & max_length

swift/llm/rlhf.py, swift/llm/sft.py, swift/llm/utils/__init__.py, swift/llm/utils/argument.py, swift/llm/utils/utils.py
=> dynamic gradient_checkpointing

swift/llm/utils/dataset.py, swift/llm/utils/preprocess.py, swift/llm/utils/template.py, swift/llm/utils/utils.py
=> fix multiprocess remove_columns

swift/llm/utils/template.py
When the batch size > 1, the media_offset in mPLUG-Owl3 needs to be padded. We use the last value of each media_offset to fill the padding. Additionally, note that the images in the same batch are stacked in order, so the value of media_offset should be incremented by the number of images preceding it
=> Fix the issue with media_offset in owl3 when batch_size > 1.

swift/llm/infer.py, swift/llm/sft.py, swift/llm/utils/utils.py
=> fix cpu infer device_map

swift/llm/utils/model.py, swift/llm/utils/template.py
fix: https://github.com/QwenLM/Qwen2-VL/issues/126
=> Fix qwen2-vl zero2/3

swift/llm/sft.py
set `find_labels` and `can_return_loss` after `ta_accelerate`, because `ta_accelerate` will wrapper original model to DistributedParallel module in TorchAcc.
=> [TorchAcc] fix: fix find_labels and can_return_loss

docs/source/Instruction/支持的模型和数据集.md, docs/source/Multi-Modal/index.md, docs/source/Multi-Modal/qwen2-vl最佳实践.md, docs/source_en/Instruction/Supported-models-datasets.md, docs/source_en/Multi-Modal/index.md, docs/source_en/Multi-Modal/qwen2-vl-best-practice.md, swift/llm/utils/model.py, swift/llm/utils/template.py, swift/utils/module_mapping.py
Model: https://modelscope.cn/models/stepfun-ai/GOT-OCR2_0
Best Practices: https://github.com/modelscope/ms-swift/issues/2122
=> support got-ocr2

swift/llm/sft.py, swift/llm/utils/template.py
=> support mllm pt

swift/llm/utils/template.py
FIX: https://github.com/modelscope/ms-swift/issues/2156, https://github.com/QwenLM/Qwen2-Audio/issues/73
=> fix qwen2-audio

docs/source/Instruction/命令行参数.md, docs/source_en/Instruction/Command-line-parameters.md, swift/llm/export.py, swift/llm/utils/template.py
FIX: https://github.com/modelscope/ms-swift/issues/2147
=> Fix qwen2 vl batch size

swift/llm/utils/template.py
In the new version, the return value of vllm has changed from a list to a tuple. This caused a problem with equality checks, which prevents the removal of the suffix.
=> fix vllm ignore suffix

swift/llm/rlhf.py
https://github.com/modelscope/ms-swift/issues/2267
=> fix lora_target_modules in PPO

.gitignore, swift/llm/eval.py, swift/llm/utils/vllm_utils.py
Fix eval dataset with vllm inference backend args.
Add following in `ms-swift/swift/llm/utils/vllm_utils.py`
```python
if self.repetition_penalty is None:
self.repetition_penalty = 1.0
if self.top_p is None:
self.top_p = 1.0
if self.top_k is None:
self.top_k = -1
```
=> fix custom vllm eval args

swift/llm/export.py
FIX https://github.com/modelscope/ms-swift/issues/2376
=> fix gptq ovis quant (inputs_embeds)

swift/llm/deploy.py
=> fix swift deploy (lmdeploy stream)

swift/tuners/peft.py
=> fix peft is_multimodal

swift/torchacc_utils.py, swift/trainers/trainers.py
Optimize padding strategy when persistent cache is enabled, so we can enjoy performance boost with little extra compilaiton.
Around 10% e2e performance improvement for TorchAcc backend.
=> [TorchAcc] Update padding strategy when using persistent cache

swift/llm/utils/template.py
Support batch flattening to avoid padding for better training performance and less memory usage. The function has the same behaviour with [DataCollatorWithFlattening](https://github.com/huggingface/transformers/blob/main/src/transformers/data/data_collator.py#L1618)
Effectively reduce peak memory for ~25% and 50% maximum training throughput improvement.
=> support batch flattening collator

MANIFEST.in, docs/source/Instruction/ReleaseNote3.0.md
=> fix manifest

docs/source/Instruction/命令行参数.md, docs/source_en/Instruction/Command-line-parameters.md, examples/train/tuners/bone/train.sh, requirements/framework.txt, swift/llm/argument/base_args/base_args.py, swift/llm/argument/train_args.py, swift/llm/argument/tuner_args.py, swift/llm/infer/utils.py, swift/llm/train/tuner.py, swift/tuners/lora_layers.py, swift/tuners/peft.py, swift/ui/llm_train/lora.py
=> Support peft0.14

examples/infer/pt/all_to_all.sh, examples/train/all_to_all/train.sh, swift/llm/template/template/emu3.py
=> train and infer scripts for emu3_gen

swift/tuners/llamapro.py
Support llamapro for multi modal models
tested ok for qwen-vl qwen2-vl internvl llama-vision
=> support multi-modal llamapro

swift/ui/llm_infer/runtime.py, swift/ui/llm_train/runtime.py
=> fix some web-ui bugs

docs/source/Instruction/命令行参数.md, docs/source_en/Instruction/Command-line-parameters.md, swift/llm/argument/base_args/template_args.py, swift/llm/template/base.py, swift/llm/template/register.py
A new 'right' parameter has been added to the truncation_strategy, corresponding to right-side truncation. This is necessary, especially in the training of multimodal large models. For instance, if an image is input at the beginning of the data but the model's output exceeds the max_length, left-side truncation alone may result in the image being cut off, causing the model to lose crucial context for generating the result.
No experiment.
=> add 'right' option for 'truncation_strategy'

swift/llm/argument/merge_args.py, swift/llm/argument/train_args.py, swift/llm/export/merge_lora.py, swift/llm/train/sft.py, swift/llm/train/tuner.py, swift/plugin/optimizer.py, swift/trainers/arguments.py, swift/trainers/mixin.py, swift/trainers/optimizers/galore/utils.py, swift/ui/llm_infer/llm_infer.py, swift/utils/__init__.py, swift/utils/import_utils.py
=> Move optimizer to create_optimizer

swift/llm/argument/rlhf_args.py, swift/llm/train/rlhf.py
=> support multi round dpo

examples/infer/demo.py, swift/llm/infer/infer_engine/infer_engine.py, swift/llm/infer/infer_engine/pt_engine.py
=> Support infer n parameter

docs/source/Instruction/命令行参数.md, docs/source_en/Instruction/Command-line-parameters.md, swift/llm/argument/infer_args.py, swift/llm/infer/infer_engine/vllm_engine.py
The [Automatic Prefix Caching](https://docs.vllm.ai/en/latest/features/automatic_prefix_caching.html) is very useful for modeling service.
This PR add argument (`--enable_prefix_caching`) for both infer and deploy mode. Prefix caching disable by default.
=> add "enable_prefix_caching" args for vllm engine.

swift/plugin/tools.py
当前的 qwen-template（tool）在多个 tools 时，会被解析为如下的格式(例如 13 个工具)
```markdown
...
✿FUNCTION✿:工具1的名称
✿ARGS✿:工具1的输入
✿RESULT✿:工具1的结果
✿FUNCTION✿:工具2的名称
✿ARGS✿:工具2的输入
✿RESULT✿:工具2的结果
✿FUNCTION✿:工具3的名称
✿ARGS✿:工具3的输入
✿RESULT✿:工具3的结果
✿FUNCTION✿:工具4的名称
✿ARGS✿:工具4的输入
✿RESULT✿:工具4的结果
✿FUNCTION✿:工具5的名称
✿ARGS✿:工具5的输入
✿RESULT✿:工具5的结果
✿FUNCTION✿:工具6的名称
✿ARGS✿:工具6的输入
✿RESULT✿:工具6的结果
✿FUNCTION✿:工具7的名称
✿ARGS✿:工具7的输入
✿RESULT✿:工具7的结果
✿FUNCTION✿:工具8的名称
✿ARGS✿:工具8的输入
✿RESULT✿:工具8的结果
✿FUNCTION✿:工具9的名称
✿ARGS✿:工具9的输入
✿RESULT✿:工具9的结果
✿FUNCTION✿:工具10的名称
✿ARGS✿:工具10的输入
✿RESULT✿:工具10的结果
✿FUNCTION✿:工具11的名称
✿ARGS✿:工具11的输入
✿RESULT✿:工具11的结果
✿FUNCTION✿:工具12的名称
✿ARGS✿:工具12的输入
✿RESULT✿:工具12的结果
✿FUNCTION✿:工具13的名称
✿ARGS✿:工具13的输入
✿RESULT✿:工具13的结果
✿FUNCTION✿:工具14的名称
✿ARGS✿:工具14的输入
✿RESULT✿:工具14的结果
```
而正确的版本，参考如下链接：
* [Qwen2 …
=> Fix qwen tool template to official format

swift/llm/template/template_inputs.py, tests/llm/test_template.py
修复 #2984 问题。多轮 tool-calling 时，message 会将 `role=tool` 内容merge 进上一条 `role=assistant` 的内容中；但是连续的 tool calling 会导致消息列表会由`user→assistant→tool→assistant→tool`变为 `user→assistant→assistant`，导致后续校验报错。
本 PR 修复了该问题，在`messages_join_observation`时也会将连续的`role=assistant`的内容进行合并，以避免上述问题。
=> fix message merging strategy  when multi-turn tool calling.

docs/source/Instruction/命令行参数.md, docs/source_en/Instruction/Command-line-parameters.md, swift/llm/argument/rlhf_args.py, swift/llm/infer/utils.py, swift/trainers/arguments.py, swift/trainers/rlhf_trainer/grpo_trainer.py, swift/utils/__init__.py, swift/utils/env.py
=> Support multiple vllms

swift/hub/hub.py
There is some error when using `swift export` to upload the model to huggingface.
``` (/projects/m000091/llm) zheminh@n08:/projects/m000091$ swift export     --model /projects/m000091/output/v11-20250226-132530/checkpoint-321-merged     --use_hf true     --push_to_hub true     --hub_model_id zheminh/Qwen2.5-32B-Instruct-1
run sh: `/projects/m000091/llm/bin/python3.12 /projects/m000091/llm/lib/python3.12/site-packages/swift/cli/export.py --model /projects/m000091/output/v11-20250226-132530/checkpoint-321-merged --use_hf true --push_to_hub true --hub_model_id zheminh/Qwen2.5-32B-Instruct-1`
[INFO:swift] Successfully registered `/projects/m000091/llm/lib/python3.12/site-packages/swift/llm/dataset/data/dataset_info.json`
[INFO:swift] Successfully loaded …
```
=> fix: error when uploading model to huggingface

docs/source/Instruction/命令行参数.md, docs/source_en/Instruction/Command-line-parameters.md, swift/llm/argument/train_args.py, swift/llm/ds_config/zero3.json
=> Support ZeRO++

swift/trainers/rlhf_trainer/grpo_trainer.py
当GRPO配置zero3时，始终会将所有参数收集到单卡推理，导致虽然设置了zero3，但实际上也跑不起来超过单卡显存的模型。即使设置了--ds3_gather_for_generation False也没用。这个PR修复了这个问题。
修复前，zero3，16卡Ascend910B，单卡65G显存，跑不起来InternVL2.5-26B，直接OOM。
修复后，同样配置环境，InternVL2.5-26B，zero3可以正常训练，且显存占用降低到单卡30GB左右，符合预期。
=> fix grpo trainer zero3 always gather parameters

swift/llm/template/template/llava.py
在我sft训练LLaVA和LLaVA-Next的过程中，发现当transformers版本大于等于4.47时，训练会报错，小于4.46时可以正常训练。报错信息和此issue #3196 相同。经过查看transformers的llava模型代码，发现在4.46版本时，模型内部对单个<image> token扩展成实际数量的image token有两套处理逻辑，第一套是传统的在模型forward内部处理，第二条是交由processor在__call__中直接对输入文本扩展，forward内部只负责scatter image feature到对应位置。在transformers 4.47以后，第一套逻辑被删掉了。但是由于本框架在处理数据时，对文本和图像是分开处理的，没有调用processor.__call__函数，因此此时image token无法被正确扩展，导致token数量不匹配报错。因此本PR参考llava-onevision和qwen的处理逻辑，修改了LlavaHfTemplate的代码进行适配。
此外，还为llava1_5_hf的TemplateMeta增加了system_prefix，防止传入带system message的信息时报错。
已经测试sft训练LLaVA和LLaVA-Next时没有问题。
Fixes #3196
=> 更新LlavaHfTemplate以适配transformers版本大于4.47时对LLaVA和LLaVA-Next模型处理图像token逻辑的修改

docs/source/Instruction/GRPO.md, docs/source_en/Instruction/GRPO.md, swift/plugin/orm.py, swift/trainers/arguments.py
https://github.com/modelscope/ms-swift/issues/3636
fix the mismatch between the parameter name and description of the cosine reward, which may cause errors when the default value is not used.
=> fix grpo cosine reward

swift/llm/template/template/gemma.py
There was a warning. Just addressing that.
```
/home/dev/src/prospero/python/external/ms-swift/swift/llm/template/template/gemma.py:118: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at /pytorch/torch/csrc/utils/tensor_new.cpp:254.)
```
=> [Gemma] Fixing the ndarray cast warning

swift/trainers/rlhf_trainer/grpo_trainer.py
add warning for unsupported model with LMDeploy turbomind backend
https://github.com/modelscope/ms-swift/issues/3785
=> grpo lmdeploy warn

swift/trainers/arguments.py, swift/trainers/rlhf_trainer/grpo_trainer.py
more log in GRPO
compatible with trl main branch
=> more grpo log

swift/llm/dataset/utils.py
In `LazyLLMDataset.__getitem__`, the loop variable `i` is modified inside the retry logic, which can lead to incorrect behavior when checking if the maximum retry attempts (`n_try_fetch`) have been reached.
For example:
If `i` = 0, it gets reassigned to `idx`, but later the condition `i == self.n_try_fetch - 1` may incorrectly evaluate because i is no longer the original loop counter.
This could cause the method to either:
- Fail too early (if `idx` happens to match `n_try_fetch - 1`).
- Fail too late (if `i` is reassigned to a smaller value).
Introduce a separate variable n_try to track the actual retry count, ensuring the correct number of attempts is enforced.
This makes the retry logic more robust and predictable.
=> Fix incorrect retry count check in LazyLLMDataset.__getitem__

swift/trainers/rlhf_trainer/grpo_trainer.py, swift/trainers/rlhf_trainer/utils.py
remove metric mask to avoid shape mismatch
=> fix grpo filter overlong

swift/tuners/peft.py
Compatible with previously trained Swift checkpoints
=> revert swift_from_pretrained

examples/train/embedding/train_gte.sh, swift/ui/base.py, swift/ui/llm_export/llm_export.py
=> Fix web-ui

docs/source/Instruction/命令行参数.md, docs/source_en/Instruction/Command-line-parameters.md, swift/llm/argument/infer_args.py, swift/llm/infer/infer_engine/vllm_engine.py
=> Support vllm quantization 

swift/trainers/rlhf_trainer/grpo_trainer.py
=> Fix grpo eval when gas > 1

swift/llm/argument/train_args.py
``` bash
export WANDB_PROJECT=llm101
CUDA_VISIBLE_DEVICES=0 \
swift sft \
--model data/models/Qwen/Qwen2.5-0.5B-Instruct \
--train_type full \
--dataset data/swift/Qwen3-SFT-Mixin/qwen3_32b_distill_1k.jsonl \
--torch_dtype bfloat16 \
--num_train_epochs 1 \
--per_device_train_batch_size 1 \
--per_device_eval_batch_size 1 \
--learning_rate 1e-5 \
--gradient_accumulation_steps 16 \
--eval_steps 50 \
--save_steps 50 \
--save_total_limit 1 \
--logging_steps 1 \
--max_length 2048 \
--output_dir runs/swift/qwen2.5-0.5b \
--system 'You are a helpful assistant.' \
--warmup_ratio 0.05 \
--dataloader_num_workers 4 \
--report_to wandb \
--attn_impl flash_attn \
--use_liger_kernel true \
--run_name …
```
=> feat: add run name support

swift/megatron/argument/megatron_args.py
Add support megatron wandb in ms-swift
Add arguments like megatron llm
https://github.com/NVIDIA/Megatron-LM/blob/89d758b28f57d71fe74a6e1b85d2f93a4302121a/megatron/training/arguments.py#L1514
``` bash
NPROC_PER_NODE=1 \
CUDA_VISIBLE_DEVICES=0 \
megatron sft \
--load data/models/Qwen/Qwen3-0.6B-mcore \
--dataset data/swift/Qwen3-SFT-Mixin/qwen3_32b_distill_1k.jsonl \
--tensor_model_parallel_size 1 \
--micro_batch_size 1 \
--global_batch_size 16 \
--recompute_granularity selective \
--train_iters 31 \
--eval_iters 5 \
--finetune true \
--cross_entropy_loss_fusion true \
--lr 1e-5 \
--lr_warmup_iters 10 \
--min_lr 1e-6 \
--save runs/test/qwen3-0.6b-megatron \
--save_interval 100 \
--max_length 2048 \
--system 'You are a helpful assistant.' \ …
```
=> feat: support megatron wandb

swift/trainers/rlhf_trainer/grpo_trainer.py
1. in some case, model forward with labels will cause logits None, we pop labels here
2. for peft model, inspect inner model to save memory with logits_to_keep parameter(super)
=> [grpo] fix labels pop and peftmodel parameter check 

docs/source/BestPractices/GRPO代码训练.md, docs/source_en/BestPractices/GRPO-Code-Training.md, examples/train/grpo/plugin/plugin.py
GRPO code training supports the execution of generated code using Judge0.
=> grpo code reward by judge0

docs/source/Instruction/命令行参数.md, docs/source_en/Instruction/Command-line-parameters.md, examples/train/long_text/sequence_parallel.sh, swift/llm/argument/base_args/model_args.py
=> support yarn

docs/source/GetStarted/SWIFT安装.md, docs/source_en/GetStarted/SWIFT-installation.md
https://github.com/modelscope/ms-swift/issues/4202
Since GRPO already supports vLLM 0.8 in https://github.com/modelscope/ms-swift/pull/4097, the warning about the vLLM version in the documentation can be removed.
=> [doc] remove vllm version warning in grpo

swift/llm/train/rlhf.py
fix a bug that the task_type of models in rlhf is set to `seq_cls` , since the default value of num_labels
=> fix task type judgement in rlhf

swift/llm/model/model/qwen.py, swift/trainers/callback.py, tests/test_align/test_template/test_video.py
https://github.com/QwenLM/Qwen2.5-VL/issues/1120
=> fix qwen2_5_vl VIDEO_TOTAL_PIXELS

swift/llm/infer/infer_engine/vllm_engine.py
PR https://github.com/modelscope/ms-swift/pull/4295 resolves the n>1 issue for the vLLM V1 Engine. However, it inadvertently causes a regression, breaking stream generation and resulting in only empty outputs
Add `stream=True` in the curl command to check it.
=> Fix vLLM engine returning empty in stream generation

swift/llm/template/template/internvl.py
When user set customized 'input_size' instead of 448, the original version will raise exception, due to the dynamic of 'num_image_token'. we change the 'num_image_token' according to the 'input_size' dynamically.
=> Update internvl.py, solve the exception when setting customized INPUT_SIZE.

swift/ui/llm_train/runtime.py
Fix #4403,  cmdline parsing error on Windows system. 
=> Fix cmdline parsing error on Windows system

docs/source/Instruction/GRPO.md, docs/source/Instruction/命令行参数.md, docs/source_en/Instruction/Command-line-parameters.md, docs/source_en/Instruction/GRPO.md, swift/trainers/rlhf_trainer/grpo_trainer.py, swift/trainers/rlhf_trainer/utils.py
This PR adds support for the move_model_batches parameter in external mode, allowing for batch-wise gathering of Zero3 model synchronization weights during LoRA training to reduce peak GPU memory usage.
=> [grpo]  support move_model_batches for external mode

swift/plugin/loss.py
---
在训练 GME Embedding 时，有可能需要在环境变量中提供 `INFONCE_HARD_NEGATIVES`。原本的代码遗漏了将其转换为 `int` 类型。
In the training of GME Embedding, it may be necessary to provide `INFONCE_HARD_NEGATIVES` via environment variables. The original code missed converting this value to an integer.
---
如果没有这段修改，在 validation 完成后计算 metrics 时将会报错：
If this modification is not included, an error will occur when computing metrics after validation:
```
[rank0]:     output = eval_loop(
[rank0]:   File "/home/tuozhi.wy/.conda/envs/gme/lib/python3.10/site-packages/transformers/trainer.py", line 4463, in evaluation_loop
[rank0]:     metrics = self.compute_metrics(
[rank0]:   File "/home/tuozhi.wy/.conda/envs/gme/lib/python3.10/site-packages/swift/trainers/trainers.py", line 75, in calculate_metric
[rank0]:     return …
```
=> fix: handle INFONCE_HARD_NEGATIVES as integer if provided

swift/llm/template/base.py, swift/trainers/sequence_parallel/ulysses.py
=> [Bug]Fix ulysses train steps, embedding negative sample length

swift/plugin/loss_scale/loss_scale.py
extend loss_scale to support last_round_with_ignore_empty_think for rag trainning
=> [loss_scale] support last_round_with_ignore_empty_think for rag

swift/trainers/rlhf_trainer/grpo_trainer.py
Fix a bug where res_context_list returned by _swift_encode contains an int (such as bos_token), which causes a string join error.
=> [grpo] fix apply_chat_template

swift/trainers/rlhf_trainer/grpo_trainer.py
Here's the translated version of your PR description and test cases:
- [✅] Bug Fix
During GRPO training with multi-turn sessions, the step method of MultiTurnScheduler returns a RolloutInferRequest containing a data_dict. However, this RolloutInferRequest is passed through the inputs_to_rolloutrequest function before the next request, which treats data_dict as a regular key and merges it into the new data_dict. This results in:
```
RolloutInferRequest.data_dict={"data_dict":{"key1":"value1","key2":"value2"}}
```
instead of the expected:
```
RolloutInferRequest.data_dict={"key1":"value1","key2":"value2"}
```
This issue worsens with each turn, making it difficult to access data_dict in the step method of MultiTurnScheduler subclasses.
Changes implemented:
1. If the input contains data_dict …
=> [grpo]Fix bug when repeatedly call inputs_to_rolloutrequest

swift/trainers/rlhf_trainer/grpo_trainer.py
fix the old_policy judgment when gradient_accumulation_steps > steps_per_generation but is not a multiple of steps_per_generation
=> [grpo] fix offpolicy check

swift/trainers/sequence_parallel/ulysses.py
fix excessive dependency: importing RepeatSampler from trl unintentionally imports vllm
=> [SP] clean up imports

swift/llm/train/sft.py
Fix storing trainer state on storage systems that do not support append or delete operations, which previously could cause training to be incorrectly marked as failed
On storage systems like HDFS that do not allow file modification or deletion, attempting to update trainer state or logging (e.g., logging.jsonl) at the end of training could fail. This caused the training job to exit abnormally and be marked as failed, even though training itself had completed successfully.
=> fix: trainer state strict saving

swift/llm/template/template/pixtral.py
- [√ ] Bug Fix
在修复loss_scale过程中，发现swift/llm/template/pixtral.PixtralTemplate._encode () 方法存在两个问题：
1. pixel_values 取值，类型传递问题
2. image_sizes 取值问题
详细说明如下：
原始代码:
```python
#/swift/llm/template/template/pixtral.PixtralTemplate._encode()
if idx_list:
image_inputs = processor.image_processor(images, patch_size=processor.patch_size, return_tensors='pt')
encoded['pixel_values'] = image_inputs['pixel_values'][0]
image_sizes = image_inputs['image_sizes'][0]
```
**问题:**
```python
encoded['pixel_values'] = image_inputs['pixel_values'][0] 多加了一个[0], 
```
- 本应传入一个四位的tensor (批次,通道,高,宽), 但实际取了第一个,传入了一个三位的tensor(通道,高,宽), 导致
```python
transformer.models.pixtral.modeling_pixtral.forward()中的
batch_size, _, height, width = pixel_values.shape
报错:
ValueError: not enough values to unpack (expected 4, got 3)
``` …
=> [template] fix/pixtral/pixel_values & image_sizes

swift/llm/argument/rlhf_args.py, swift/llm/infer/protocol.py, swift/llm/infer/rollout.py, swift/trainers/rlhf_trainer/grpo_trainer.py, swift/trainers/rlhf_trainer/vllm_client.py, swift/utils/__init__.py, swift/utils/import_utils.py
1. Set 'self.model_kwarg_keys' to be compatible with trl 0.2.
2. Optimize the logic for retrieving 'last_hidden_state' in liger_loss calculation, and add parameter checking for 'logits_to_keep'.
3. Move the logic for computing 'ref_logps' to the rollout phase to avoid redundant calculations when 'num_iterations' > 1.
4. add optional 'device' argument for server mode in init_communicator method
=> [grpo] compatible with trl 0.2

swift/llm/argument/base_args/model_args.py
- [ O ] Bug Fix
Updated the logic to parse `rope_scaling` from the `model config`, and to take `original_max_position_embeddings` to re-calculate `max_model_len`
=> Fix: init_rope_scaling from model config first

swift/trainers/rlhf_trainer/ppo_trainer.py
When use DDP for ppo, after train succss, and save model will return AttributeError. 
See this issue https://github.com/modelscope/ms-swift/issues/2289. 
Found similar issue in trl repo, and someone gave a solution https://github.com/huggingface/trl/issues/2375#issuecomment-2837664502
After manually unwrap ddp model, problem solved
When use ppo, after train succss, and save model will return AttributeError
```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/app/main.py", line 355, in <module>
[rank0]:     main()
[rank0]:   File "/app/main.py", line 332, in main
[rank0]:     raise e
[rank0]:   File "/app/main.py", line 320, in main
[rank0]:     runner.run()
[rank0]:   File "/app/finetune/v2/ppo.py", line 100, in run
[rank0]:     return self.train(trainer)
[rank0]:   File …
```
=> Fix: Use DDP for PPO traning will cause `AttributeError: 'DistributedDataParallel' object has no attribute 'policy'`

swift/plugin/callback.py
The patience counter in the EarlyStopping plugin was not reset after a new best loss was found, leading to premature termination of training. This patch resets the counter on improvement.
=> fix: Fix bug in EarlyStop plugin patience counter

examples/infer/lmdeploy/batch_ddp.sh, swift/llm/infer/infer_engine/lmdeploy_engine.py
Fix a bug in LMDeploy DDP inference
```
[rank1]: TypeError: LmdeployEngine.__init__() got an unexpected keyword argument 'devices'
```
=> [infer] fix lmdeploy ddp infer

swift/llm/template/template/glm.py, swift/plugin/agent_template/__init__.py, swift/plugin/agent_template/glm4.py
This PR adds support for GLM-4.5 agent (function call) training in ms-swift.
Key updates:
1. Added GLM4_5AgentTemplate in plugin/agent_template/glm4.py to support training GLM-4.5 function call agents.
2. Enhanced suffix appending logic: in the final generation round, check if the output already ends with a stop word, and skip appending the suffix if so to avoid redundancy.
- Training successfully runs on 8×A100 (80GB) with GLM-4.5 agent configuration.
=> [model] support glm-4.5 agent

swift/trainers/rlhf_trainer/grpo_trainer.py
Fix: prevent logging of filtered-out samples when dynamic sampling is enabled
moved the logging logic after the filtering step
=> [grpo] fix log error in dynamic sampling

swift/llm/model/model/qwen.py, swift/llm/model/patcher.py, swift/llm/model/register.py
`Qwen3ForSequenceClassification` doesn't define its own `__init__` method:
```python
class Qwen3ForSequenceClassification(GenericForSequenceClassification, Qwen3PreTrainedModel):
pass
```
This causes a bug when used with DeepSpeed's Zero context manager, which patches all module init methods during entry and restores them during exit:
```python
def unpatch_init_and_builtins(self):
...
def _enable_class(cls):
if '__init__' in cls.__dict__:
cls._old_init = cls.__init__
cls.__init__ = partition_after(cls.__init__)
for subclass in get_all_subclasses(torch.nn.modules.module.Module):
_enable_class(subclass)
def unpatch_init_and_builtins(self):
if self.patched:
def _disable_class(cls):
if hasattr(cls, '_old_init'):
cls.__init__ = cls._old_init
for subclass in …
```
=> [bugfix] fix Qwen3ForSequenceClassification zero3

swift/megatron/model/gpt/__init__.py
The `qwen3_coder` model type was not registered causing the `megatron_model_meta` to being set to None causing a crash.
=> register qwen3_coder

swift/llm/template/base.py
=> fix embedding encode

swift/llm/template/base.py, swift/plugin/loss_scale/config/ignore_empty_think.json, swift/plugin/loss_scale/loss_scale.py, swift/trainers/rlhf_trainer/utils.py
1. Add loss-scale support for chord SFT loss.
2. Update the is_binary-checking logic in the template  loss_scale.
3. Ensure chord remains compatible with earlier transformers versions (e.g., 4.51).
=> chord support loss_scale & update template loss_scale is_binary

swift/trainers/optimizers/galore/utils.py, swift/trainers/sequence_parallel/ulysses.py, swift/utils/__init__.py, swift/utils/torch_utils.py
=> fix galore
