modelscope/ms-swift

examples/pytorch/llm/llm_infer.py, examples/pytorch/llm/llm_sft.py, examples/pytorch/llm/run_infer.sh, examples/pytorch/llm/run_sft.sh, examples/pytorch/llm/utils/dataset.py, examples/pytorch/llm/utils/models.py
1. add comment
2. chatglm2 v1.0.6 -> v1.0.7
3. fix dataset_sample
4. add parameters to .sh
=> add comment

examples/pytorch/llm/README.md, examples/pytorch/llm/README_CN.md, examples/pytorch/llm/scripts/qwen_7b/qlora_ddp/sft.sh, examples/pytorch/llm/scripts/qwen_7b_chat/qlora/sft.sh, examples/pytorch/llm/scripts/qwen_7b_chat/qlora_ddp/sft.sh, examples/pytorch/llm/scripts/qwen_vl/lora_ddp/infer.sh, examples/pytorch/llm/scripts/qwen_vl/lora_ddp/sft.sh, examples/pytorch/llm/scripts/qwen_vl/qlora_ddp/infer.sh, examples/pytorch/llm/scripts/qwen_vl/qlora_ddp/sft.sh, examples/pytorch/llm/scripts/qwen_vl_chat/lora_ddp/infer.sh, examples/pytorch/llm/scripts/qwen_vl_chat/lora_ddp/sft.sh, examples/pytorch/llm/scripts/qwen_vl_chat/qlora/infer.sh, examples/pytorch/llm/scripts/qwen_vl_chat/qlora/sft.sh, examples/pytorch/llm/scripts/qwen_vl_chat/qlora_ddp/infer.sh, examples/pytorch/llm/scripts/qwen_vl_chat/qlora_ddp/sft.sh, examples/pytorch/llm/src/llm_infer.py, examples/pytorch/llm/src/llm_sft.py, examples/pytorch/llm/src/utils/dataset.py, examples/pytorch/llm/src/utils/model.py, examples/pytorch/llm/src/utils/preprocess.py, examples/pytorch/llm/src/utils/trainer_patch.py, examples/pytorch/llm/src/utils/utils.py, swift/utils/__init__.py
1. add qwen-vl, qwen-vl-chat
2. add coco-en dataset
3. add sh (qwen-vl-chat, qwen-vl)
4. fix infer bug
5. add max_steps argument
6. add batched map
=> llm support multimodal

examples/pytorch/llm/src/llm_sft.py
1. fix bug: rank0 memory is high
=> fix ddp rank0 memory bug

README.md, README_CN.md, examples/pytorch/llm/README.md, examples/pytorch/llm/README_CN.md, examples/pytorch/llm/scripts/qwen_7b/qlora_ddp/sft.sh, examples/pytorch/llm/scripts/qwen_7b_chat/full/sft.sh, examples/pytorch/llm/scripts/qwen_7b_chat/lora_ddp/sft.sh, examples/pytorch/llm/scripts/qwen_7b_chat/qlora/sft.sh, examples/pytorch/llm/scripts/qwen_7b_chat/qlora_ddp/sft.sh, examples/pytorch/llm/scripts/qwen_agent/qlora_ddp/sft.sh, examples/pytorch/llm/scripts/qwen_vl/qlora_ddp/sft.sh, examples/pytorch/llm/scripts/qwen_vl_chat/lora_ddp/sft.sh, examples/pytorch/llm/scripts/qwen_vl_chat/qlora/sft.sh, examples/pytorch/llm/scripts/qwen_vl_chat/qlora_ddp/sft.sh, examples/pytorch/llm/src/llm_sft.py, examples/pytorch/llm/src/utils/dataset.py, examples/pytorch/llm/src/utils/model.py, examples/pytorch/llm/src/utils/preprocess.py, examples/pytorch/llm/src/utils/utils.py, swift/trainers/trainers.py
1. sync baichuan2 PR
2. fix template bug
=> fix template bug

README.md, README_CN.md, examples/pytorch/llm/scripts/qwen_7b_chat/full/sft.sh, examples/pytorch/llm/src/llm_infer.py, examples/pytorch/llm/src/llm_sft.py, examples/pytorch/llm/src/utils/dataset.py, examples/pytorch/llm/src/utils/model.py, swift/trainers/__init__.py, swift/trainers/arguments.py, swift/trainers/mixin.py, swift/trainers/trainer_patch.py, swift/trainers/utils.py
1. add feat: only save model
2. fix chatglm2 device_map bug
3. fix coco-en bug
=> add feat: only save model

examples/pytorch/llm/scripts/seqgpt_560m/full/sft.sh, examples/pytorch/llm/src/llm_sft.py
1. fix ddp+graidient_checkpointing bug
=> fix ddp+graidient_checkpointing bug

README.md, README_CN.md, examples/pytorch/llm/README.md, examples/pytorch/llm/README_CN.md, examples/pytorch/llm/scripts/seqgpt_560m/full/infer.sh, examples/pytorch/llm/scripts/seqgpt_560m/full/sft.sh, examples/pytorch/llm/src/llm_sft.py, examples/pytorch/llm/src/utils/dataset.py, examples/pytorch/llm/src/utils/utils.py
1. add dataset
2. add special dataset for seqgpt-560m
=> Add seqgpt dataset

examples/pytorch/llm/README.md, examples/pytorch/llm/README_CN.md, examples/pytorch/llm/scripts/qwen_7b_chat/lora_mp_ddp/sft.sh, examples/pytorch/llm/src/llm_sft.py
1. training_args._frozen = False
=> set training_args._frozen=False

examples/pytorch/llm/src/utils/model.py
hello!
I fix issue: https://github.com/modelscope/swift/issues/69
=> fix httperror

examples/pytorch/llm/README.md, examples/pytorch/llm/README_CN.md, examples/pytorch/llm/scripts/qwen_7b_chat/lora/merge_lora_and_infer.sh, examples/pytorch/llm/scripts/qwen_7b_chat/lora/sft.sh, examples/pytorch/llm/scripts/qwen_7b_chat/qlora/merge_lora_and_infer.sh, examples/pytorch/llm/src/merge_lora_and_infer.py, swift/utils/llm_utils.py
1. add merge_lora.sh, merge_lora.py
=> update feat: merge lora

examples/pytorch/llm/README.md, examples/pytorch/llm/README_CN.md, examples/pytorch/llm/scripts/baichuan2_7b/qlora/sft.sh, examples/pytorch/llm/scripts/internlm_20b/qlora/sft.sh, examples/pytorch/llm/scripts/internlm_20b_chat/qlora/infer.sh, examples/pytorch/llm/scripts/internlm_20b_chat/qlora/sft.sh, examples/pytorch/llm/scripts/qwen_7b/lora_ddp/infer.sh, examples/pytorch/llm/scripts/qwen_7b_chat/lora_mp_ddp/infer.sh, examples/pytorch/llm/scripts/qwen_7b_chat/lora_mp_ddp/sft.sh, examples/pytorch/llm/scripts/qwen_7b_chat/qlora/infer.sh, examples/pytorch/llm/scripts/qwen_7b_chat/qlora/sft.sh, examples/pytorch/llm/scripts/qwen_7b_chat/qlora_ddp/infer.sh, examples/pytorch/llm/src/utils/model.py
=> Add internlm agent

README.md, README_CN.md, examples/pytorch/llm/README.md, examples/pytorch/llm/README_CN.md, examples/pytorch/llm/scripts/qwen_7b_chat/qlora_ddp/sft.sh, examples/pytorch/llm/src/utils/model.py
1. fix internlm-20b-chat model_id
=> fix internlm-20b-chat model_id

requirements/framework.txt, swift/tuners/base.py, swift/tuners/lora.py, swift/tuners/side.py, tests/tuners/test_swift_base.py
1. Replace loralib with code copied into lora.py (because loralib does not works well with float16)
2. Fix bug in side tuner
3. Fix bug in qlora to lora
4. Add some unittest
=> Fix dtype error

examples/pytorch/llm/README.md, examples/pytorch/llm/README_CN.md, examples/pytorch/llm/scripts/qwen_7b_chat/lora_ddp/infer.sh, examples/pytorch/llm/scripts/qwen_7b_chat/lora_ddp/sft.sh, examples/pytorch/llm/src/llm_sft.py, examples/pytorch/llm/src/utils/argument.py, swift/trainers/arguments.py, swift/trainers/mixin.py, tests/trainers/test_trainer.py
1. push_ms_hub: Compatible with transformers>=4.32
=> fix push to hub bug

examples/pytorch/llm/README.md, examples/pytorch/llm/README_CN.md, examples/pytorch/llm/scripts/seqgpt_560m/full_ddp/infer.sh, examples/pytorch/llm/scripts/seqgpt_560m/full_ddp/sft.sh, examples/pytorch/llm/src/llm_sft.py, examples/pytorch/llm/src/utils/argument.py, swift/trainers/__init__.py, swift/trainers/mixin.py, swift/utils/llm_utils.py
1. fix https://github.com/modelscope/swift/issues/107
2. update seqgpt_560m sh
=> fix resume from checkpointing bug

examples/pytorch/llm/scripts/openbuddy_llama2_70b_chat/qlora_ddp_ds/infer.sh, examples/pytorch/llm/scripts/openbuddy_llama2_70b_chat/qlora_ddp_ds/sft.sh, examples/pytorch/llm/scripts/openbuddy_llama2_70b_chat/qlora_mp/infer.sh, examples/pytorch/llm/scripts/openbuddy_llama2_70b_chat/qlora_mp/sft.sh, examples/pytorch/llm/scripts/openbuddy_mistral_7b_chat/lora_ddp_ds/infer.sh, examples/pytorch/llm/scripts/openbuddy_mistral_7b_chat/lora_ddp_ds/sft.sh, examples/pytorch/llm/src/llm_infer.py, examples/pytorch/llm/src/llm_sft.py, examples/pytorch/llm/src/utils/model.py, examples/pytorch/llm/src/utils/preprocess.py
=> fix openbuddy template

README.md, README_CN.md, examples/pytorch/llm/README.md, examples/pytorch/llm/README_CN.md, examples/pytorch/llm/scripts/chatglm3_6b_32k/lora_ddp_ds/sft.sh, examples/pytorch/llm/scripts/chatglm3_6b_32k/rome.sh, swift/llm/rome.py, swift/llm/sft.py, swift/llm/utils/argument.py, swift/tuners/__init__.py, swift/tuners/adapter.py, swift/tuners/base.py, swift/tuners/lora.py, swift/tuners/mapping.py, swift/tuners/neftune.py, swift/tuners/prompt.py, swift/tuners/restuning.py, swift/tuners/rome/compute_u.py, swift/tuners/rome/compute_v.py, swift/tuners/rome/rome.py, swift/tuners/rome/rome_hparams.py, swift/tuners/side.py, swift/tuners/utils.py, tests/tuners/test_neft.py
1. Add NEFTune
2. Support ROME for ChatGLM series models
=> Add neftune

swift/llm/utils/model.py
修复issue: https://github.com/modelscope/swift/issues/184
=> Fix the slow inference speed bug in qwen AutoGPTQ

README.md, README_CN.md, docs/source/LLM/支持的模型和数据集.md, docs/source/LLM/自定义与拓展.md, docs/source/LLM/自我认知微调最佳实践.md, scripts/utils/test_readme.py, swift/llm/infer.py, swift/llm/sft.py, swift/llm/utils/argument.py, swift/llm/utils/dataset.py, swift/llm/utils/model.py, swift/llm/utils/utils.py, swift/utils/__init__.py, swift/utils/run_utils.py, swift/utils/utils.py, tests/llm/data/alpaca.csv, tests/llm/data/alpaca.jsonl, tests/llm/data/alpaca2.csv, tests/llm/data/chatml.jsonl, tests/llm/data/conversations.jsonl, tests/llm/data/swift_multi.json, tests/llm/data/swift_multi.jsonl, tests/llm/data/swift_pre.csv, tests/llm/data/swift_pre.jsonl, tests/llm/data/swift_single.csv, tests/llm/data/swift_single.jsonl, tests/llm/test_run.py
update multi-line input, custom_dataset citest
=> update multi-line input (infer)

swift/tuners/base.py, swift/tuners/lora.py, swift/tuners/lora_layers.py, swift/tuners/utils.py, tests/tuners/test_extra_state_dict.py
1. Add requires_grad=True to extra_state_keys
2. Add save logic to LoRA.modules_to_save
=> Fix model saving in new format

docs/source/LLM/命令行参数.md, swift/llm/infer.py
issue: https://github.com/modelscope/swift/issues/222
=> Fix merge_lora & model_cache_dir bug

swift/llm/utils/vllm_utils.py
修复在modelscope notebook中使用vllm会出现HttpError的问题
=> fix vllm env bug

examples/pytorch/llm/scripts/yi_vl_6b_chat/lora/sft.sh
fix https://github.com/modelscope/swift/issues/346
=> fix yi-vl finetune error

README.md, README_CN.md, docs/source/LLM/支持的模型和数据集.md, swift/llm/utils/model.py, swift/llm/utils/utils.py, swift/tuners/lora_layers.py, tests/llm/test_run.py
1. update model name: openbmb-minicpm-2b
2. fix issue: https://github.com/modelscope/swift/issues/342
=> Fix issue 342

swift/llm/utils/model.py, swift/llm/utils/protocol.py
1. fix deepseek moe device_map: https://github.com/modelscope/swift/issues/474
2. fix infer_backend='pt' & swift inference_client
=> fix deepseek moe device_map

swift/ui/llm_infer/llm_infer.py, swift/ui/llm_infer/model.py, swift/ui/llm_infer/runtime.py
fix web_ui _deploy start_time and log bug.
=> fix web_ui time and log bug

swift/llm/deploy.py, swift/llm/utils/utils.py, swift/llm/utils/vllm_utils.py
=> fix deploy safe_response

setup.cfg, swift/tuners/peft.py
Fix peft Adalora does not support device_map
=> Fix Adalora with devicemap

swift/trainers/mixin.py
=> fix save dir (additional_files)

swift/utils/metric.py
Sometimes when compute metric rouge for long text, the maximum recursion depth is exceeded. Fix recursion depth to resolve this bug.
=> fix rouge recursion depth

examples/pytorch/llm/scripts/grok-1/lora_ddp_ds/infer.sh, examples/pytorch/llm/scripts/grok-1/lora_ddp_ds/sft.sh, examples/pytorch/llm/scripts/grok-1/lora_ddp_ds/zero3.json
=> add missing files

swift/llm/app_ui.py
issue: https://github.com/modelscope/swift/issues/645
=> fix typing hint

requirements/framework.txt, swift/ui/llm_train/runtime.py, swift/utils/metric.py
Fix plot cannot be showed in some system
=> fix plot error

docs/source/LLM/命令行参数.md, docs/source_en/LLM/Command-line-parameters.md, swift/llm/utils/argument.py
Fix the compatibility with the latest accelerate lib.
=> change the default value of ddp_backend

swift/ui/llm_infer/runtime.py
Fix the deploy log cannot be showed with correct format
=> fix ui log

swift/llm/utils/dataset.py
=> compatible with old versions of modelscope

swift/llm/sft.py, swift/llm/utils/template.py
=> Fix data_collator

docs/source/LLM/Benchmark.md
=> fix anchor

swift/llm/utils/utils.py
Avoid the occurrence of repeated words in sentence
e.g. 图中<有有>四只羊。 -> 图中有四只羊。
=> Fix stream 0415

docs/source/Multi-Modal/index.md
=> 修改Qwen-Audio最佳实践的链接

examples/pytorch/llm/scripts/codeqwen1half_7b_chat_awq/lora/sft.sh
fix codeqwen1half_7b_chat_awq sft script
=> fix script

swift/ui/llm_infer/runtime.py, swift/ui/llm_train/runtime.py
=> Support win32 for web-ui

swift/ui/llm_infer/llm_infer.py
Fix a bug that may cause infer error after changes of compatible with win32
=> Fix inference bug in web-ui

swift/llm/bug_test.py, swift/llm/utils/dataset.py
=> fix msbench bug

swift/llm/utils/argument.py
=> fix dtype='AUTO' -> 'bf16' bug

swift/llm/infer.py
=> fix `swift infer --model_type` & vllm bugs

swift/llm/utils/template.py
FIX ISSUE: https://github.com/modelscope/swift/issues/796
=> fix minicpm-v2 template.encode

swift/trainers/mixin.py
=> fix typo: update mixin.py

swift/llm/export.py, swift/llm/utils/template.py
FIX: max_length & inputs & multimodal model (keyError)
=> fix inputs & multimodal model bug

swift/ui/llm_train/lora.py
=> fix ui lora_dtype

swift/llm/utils/argument.py, tests/llm/test_run.py
=> Fix infer default dtype

docs/source/LLM/Grok训练和推理.md, docs/source/LLM/命令行参数.md, docs/source_en/LLM/Command-line-parameters.md, docs/source_en/LLM/Grok-1-best-practice.md, examples/pytorch/llm/scripts/dbrx-instruct/lora_mp/sft.sh, examples/pytorch/llm/scripts/grok-1/lora_ddp_ds/sft.sh, examples/pytorch/llm/scripts/llama2_70b_chat/qlora_fsdp/sft.sh, examples/pytorch/llm/scripts/xverse_moe_a4_2b/lora/sft.sh, swift/llm/infer.py, swift/llm/utils/argument.py
=> fix merge_lora_dtype

README.md, README_CN.md, docs/source/GetStarted/使用tuners.md, docs/source_en/GetStarted/Tuners.md
Update docs to describe more tuners
=> Update tuner docs

swift/llm/utils/dataset.py
1. 当dataset_test_ratio为1时，train_dataset为None. 该策略在swift infer时很有用.
English:
1. When dataset_test_ratio is 1, train_dataset is None. This strategy is useful during swift inference.
=> fix dataset_test_ratio=1

docs/source/LLM/命令行参数.md, docs/source_en/LLM/Command-line-parameters.md, scripts/benchmark/generate_report.py, swift/llm/utils/argument.py
Support epoch based saving and evaluation
=> support epoch based saving

swift/llm/utils/dataset.py
fix list index out of range bugs of model_name and model_author in _preprocess_self_cognition_dataset
=> fix list index out of range bugs of model_name and model_author

swift/llm/tuner.py
=> fix lisa cannot show a correct trainable parameters

README_CN.md
=> fix doc link error

docs/source_en/LLM/LLM-fine-tuning.md
replace dataset name with dataset path from modelscope
.
=> replace dataset name with dataset path from modelscope

docs/source/LLM/LLM微调文档.md
replace dataset name with modelscope dataset id
=> replace dataset name with modelscope dataset id

swift/llm/utils/argument.py, swift/llm/utils/dataset.py
=> fix val_sample

docs/source/LLM/命令行参数.md, docs/source_en/LLM/Command-line-parameters.md, swift/llm/utils/model.py
Fix code and support more models' local repo dir.
=> Add more models local repo support

swift/llm/utils/model.py, swift/llm/utils/utils.py
Fix the is_unsloth_available logic to avoid the version dependency of trl
=> Fix the available logic of unsloth

swift/llm/utils/model.py, swift/llm/utils/template.py
=> support yi-1.5 series

swift/llm/utils/model.py
=> fix deepseek-v2-chat

swift/llm/export.py
FIX ISSUE: https://github.com/modelscope/swift/issues/907
=> fix export self-cognition

swift/hub/api.py, swift/hub/errors.py, swift/llm/sft.py, swift/trainers/mixin.py, swift/tuners/utils.py, swift/ui/app.py, swift/ui/llm_train/dataset.py, swift/ui/llm_train/quantization.py
1. Remove annoying logs
2. Print sample when using packing=True
3. Will not save tokenizer when lora training (or other training method with extra modules)
4. Fix offload not work in ddp
5. Add a star beggar in UI
6. Add quant_method in UI
=> A bunch of small features

README.md, README_CN.md, docs/source/LLM/命令行参数.md, docs/source_en/LLM/Command-line-parameters.md, requirements/framework.txt, swift/llm/tuner.py, swift/llm/utils/argument.py, swift/trainers/mixin.py, swift/tuners/__init__.py, swift/tuners/lora_layers.py, swift/tuners/peft.py
1. Support peft 0.11.0
2. Support boft/vera/pissa
=> Support peft 0.11.0

swift/llm/deploy.py, swift/llm/utils/vllm_utils.py
=> fix vllm eos_token

swift/llm/utils/argument.py
=> fix typing

docs/source/Multi-Modal/minicpm-v-2.5最佳实践.md, docs/source/Multi-Modal/minicpm-v-2最佳实践.md, swift/llm/utils/model.py
=> Fix minicpm device map

docs/source/LLM/命令行参数.md, docs/source_en/LLM/Command-line-parameters.md, requirements/framework.txt, swift/llm/infer.py, swift/llm/utils/argument.py, tests/llm/test_run.py
=> update framework: transformers==4.41

swift/llm/infer.py, swift/llm/utils/argument.py
=> fix pt deploy lora

swift/llm/utils/template.py
=> Add copy to template encode

README.md, README_CN.md, docs/source/Multi-Modal/minicpm-v-2最佳实践.md, swift/llm/utils/argument.py, swift/llm/utils/template.py
=> fix minicpm-v

swift/ui/app.py, swift/ui/llm_infer/runtime.py
=> Fix gradio conccurency limit

swift/llm/utils/argument.py
=> fix arguments

docs/source/LLM/自定义与拓展.md, docs/source_en/LLM/Customization.md, examples/pytorch/llm/custom.py
=> fix custom

swift/llm/app_ui.py
issue: https://github.com/modelscope/swift/issues/1034
=> fix app_ui host & port

swift/llm/sft.py, swift/llm/utils/model.py
FIX ISSUE: https://github.com/modelscope/swift/issues/1027
=> fix phi3-vision bug

swift/llm/utils/model.py
=> fix deepseek-vl

swift/llm/sft.py, swift/llm/utils/argument.py, swift/llm/utils/model.py
https://github.com/modelscope/swift/issues/1048#issuecomment-2146895776
=> fix argument

swift/llm/utils/argument.py
=> add rope_scaling in imported infer keys

swift/llm/utils/preprocess.py
=> fix swift preprocessor

docs/source/LLM/自定义与拓展.md, docs/source_en/LLM/Customization.md, tests/llm/data/swift_#:#.jsonl, tests/llm/test_run.py
=> Fix windows

swift/llm/accelerator.py, swift/llm/tuner.py, swift/torchacc_utils.py, swift/trainers/mixin.py, swift/utils/torch_utils.py, swift/utils/utils.py
Revised the torchacc-related interfaces to accommodate torchacc 2.3 and transformers 4.40.2; added support for DDP's save and load checkpoint functionality.
=> [TorchAcc] Update to TorchAcc2.3 and transformers 4.40.2

swift/llm/utils/argument.py, swift/llm/utils/client_utils.py, swift/llm/utils/model.py, swift/llm/utils/preprocess.py, swift/llm/utils/protocol.py, tests/llm/test_run2.py
FIX ISSUE: https://github.com/modelscope/swift/issues/1091
=> fix glm4v-merge_lora

swift/llm/utils/dataset.py
=> fix local dataset

docs/source/Multi-Modal/internvl最佳实践.md, docs/source_en/Multi-Modal/internvl-best-practice.md, swift/llm/utils/template.py
https://github.com/modelscope/swift/issues/1116
https://github.com/modelscope/swift/issues/1114
=> fix internvl template

docs/source/LLM/支持的模型和数据集.md, docs/source_en/LLM/Supported-models-datasets.md, swift/llm/utils/model.py
=> support codestral_22b

docs/source/LLM/命令行参数.md, docs/source_en/LLM/Command-line-parameters.md, swift/llm/utils/argument.py, swift/llm/utils/model.py, swift/llm/utils/vllm_utils.py
=> fix eval args

swift/llm/utils/model.py
=> fix phi3-small

swift/ui/llm_infer/llm_infer.py, swift/ui/llm_infer/model.py
=> Fix/web UI 0617

swift/llm/utils/model.py
=> fix hf download

swift/llm/agent/utils.py, swift/llm/utils/argument.py, swift/trainers/kto_trainer.py
=> fix kto bugs

swift/llm/utils/model.py, swift/llm/utils/preprocess.py
=> Fix preprocessor

swift/ui/llm_train/advanced.py, swift/ui/llm_train/hyper.py, swift/ui/llm_train/llm_train.py, swift/ui/llm_train/quantization.py, swift/ui/llm_train/save.py, swift/ui/llm_train/self_cog.py
=> refactor ui

docs/source/LLM/自定义与拓展.md, docs/source_en/LLM/Customization.md, swift/llm/utils/dataset.py, swift/llm/utils/preprocess.py
Custom agent dataset training support
=> Custom agent dataset training support

docs/source/LLM/Agent微调最佳实践.md, docs/source_en/LLM/Agent-fine-tuning-best-practice.md, docs/source_en/LLM/Customization.md
=> update agent doc

swift/llm/rlhf.py, swift/llm/sft.py
=> Fix sk will be uploaded

swift/llm/utils/template.py
FIX: https://github.com/modelscope/swift/pull/1183
=> fix glm4v images

examples/pytorch/llm/scripts/torchacc/baichuan2_13b_chat/acc_lora_dp_sft.sh, examples/pytorch/llm/scripts/torchacc/baichuan2_13b_chat/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/chatglm3_6b/acc_lora_dp_sft.sh, examples/pytorch/llm/scripts/torchacc/chatglm3_6b/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/llama2_13b_chat/acc_lora_dp_sft.sh, examples/pytorch/llm/scripts/torchacc/llama2_13b_chat/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/llama3_8b_instruct/acc_lora_dp_sft.sh, examples/pytorch/llm/scripts/torchacc/llama3_8b_instruct/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/qwen1half_14b_chat/acc_lora_dp_sft.sh, examples/pytorch/llm/scripts/torchacc/qwen1half_14b_chat/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/qwen1half_32b_chat/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/qwen_72b_chat/acc_full_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/qwen_72b_chat/acc_lora_fsdp_sft.sh, examples/pytorch/llm/scripts/torchacc/yi_34b_chat/acc_lora_fsdp_sft.sh, swift/trainers/trainers.py
Cache the compiled results and remove some xla flags
=> [TorchAcc] Cache the compiled results and remove some xla flags

swift/llm/utils/template.py, swift/llm/utils/utils.py
=> fix minicpm-v data_collator

swift/llm/utils/dataset.py, swift/llm/utils/preprocess.py
=> Fix ConversationPreprocessor loading

swift/llm/utils/dataset.py, swift/utils/torch_utils.py
=> Fix map cache on multi node

swift/ui/app.py
=> add in_browswer

README.md, README_CN.md, swift/llm/utils/template.py
1. FIX https://github.com/modelscope/swift/issues/1219, https://github.com/modelscope/swift/issues/1216, https://github.com/THUDM/GLM-4/issues/233
=> Fix glm4v batch size

swift/llm/utils/model.py, swift/llm/utils/utils.py, swift/utils/logger.py, swift/utils/torch_utils.py
=> Add debug log support

swift/llm/utils/dataset.py, swift/llm/utils/media.py
=> Add new dataset

swift/llm/utils/dataset.py
=> fix refcoco

swift/tuners/base.py, swift/tuners/peft.py, swift/tuners/utils.py, swift/ui/llm_eval/llm_eval.py, swift/ui/llm_export/llm_export.py, swift/ui/llm_infer/llm_infer.py, tests/tuners/test_scetuning.py, tests/tuners/test_swift_restuning.py
(cherry picked from commit da5e1dfc4966b3010bf1ab8a785d1751732a3682)
=> reset snapshot_download to modelscope

swift/llm/utils/preprocess.py
=> fix output empty will be filtered

swift/tuners/llamapro.py, swift/tuners/module_mapping.py
=> fix llamapro

swift/llm/deploy.py
FIX: https://github.com/modelscope/swift/issues/1277
=> fix xcomposer deploy

swift/llm/infer.py, swift/llm/tuner.py, swift/llm/utils/utils.py, swift/tuners/module_mapping.py
1. Support llamapro merge
2. Support quantized training or eetq and hqq
=> Fix llamapro merge and quantized training

docs/source/Multi-Modal/vLLM推理加速文档.md, docs/source_en/Multi-Modal/vllm-inference-acceleration.md, swift/llm/deploy.py, swift/llm/infer.py, swift/llm/utils/template.py, swift/llm/utils/vllm_utils.py, swift/utils/utils.py
FIX: https://github.com/modelscope/swift/issues/1290
=> fix florence & deploy

swift/llm/utils/model.py
https://github.com/modelscope/swift/issues/1299
=> fix florence

swift/llm/utils/client_utils.py, swift/llm/utils/utils.py, swift/ui/llm_eval/eval.py, swift/ui/llm_infer/llm_infer.py, swift/ui/llm_train/advanced.py, swift/ui/llm_train/dataset.py, swift/ui/llm_train/hyper.py, swift/ui/llm_train/llm_train.py, swift/ui/llm_train/model.py, swift/ui/llm_train/save.py
1. Simplify UI
2. Support media_infer_type == 'dialogue', disable image input
3. Support tool role in inference_client
4. Fix bugs in UI
=> Refactor UI and fix some bugs

swift/ui/llm_eval/eval.py
=> fix dependency

swift/llm/utils/argument.py
=> support lr_scheduler_kwargs

docs/source/LLM/命令行参数.md, docs/source_en/LLM/Command-line-parameters.md, swift/llm/utils/argument.py
=> support warmup_stable_decay

swift/ui/llm_train/llm_train.py
=> fix web-ui

swift/llm/utils/media.py, swift/utils/__init__.py, swift/utils/utils.py
(cherry picked from commit beb6aaa457e550aae9f2daf7736af8a5119106ca)
Fix fcntl is not platform compatible
=> fix filelock

docs/source/LLM/VLLM推理加速与部署.md, docs/source/LLM/自定义与拓展.md, docs/source_en/LLM/Customization.md, docs/source_en/LLM/VLLM-inference-acceleration-and-deployment.md, swift/llm/utils/vllm_utils.py
=> fix generation_info efficiency

docs/source/LLM/Agent微调最佳实践.md, docs/source/LLM/LLM微调文档.md, docs/source/LLM/LLM量化文档.md, docs/source/LLM/index.md, docs/source/LLM/自我认知微调最佳实践.md, docs/source_en/LLM/LLM-quantization.md, examples/pytorch/llm/scripts/atom_7b_chat/lora/sft.sh, examples/pytorch/llm/scripts/codeqwen1half_7b_chat/lora/sft.sh, examples/pytorch/llm/scripts/dbrx-instruct/lora_mp/sft.sh, examples/pytorch/llm/scripts/deepseek-v2-chat/lora_mp/sft.sh, examples/pytorch/llm/scripts/internlm2_7b_sft_chat/lora/sft.sh, swift/llm/utils/utils.py
=> fix sh ddp_backend

examples/pytorch/llm/scripts/deepseek-v2-chat/lora_mp/sft.sh
=> fix a file path

swift/llm/utils/template.py, swift/llm/utils/vision_utils.py
=> Internvl2 support video

docs/source/LLM/VLLM推理加速与部署.md, docs/source/Multi-Modal/MLLM部署文档.md, docs/source/Multi-Modal/vLLM推理加速文档.md, docs/source_en/LLM/VLLM-inference-acceleration-and-deployment.md, docs/source_en/Multi-Modal/vllm-inference-acceleration.md, swift/llm/deploy.py, swift/llm/eval.py, swift/llm/utils/__init__.py, swift/llm/utils/argument.py, swift/llm/utils/client_utils.py, swift/llm/utils/lmdeploy_utils.py, swift/llm/utils/protocol.py, swift/llm/utils/utils.py
=> fix openai api

swift/llm/deploy.py, swift/llm/infer.py
FIX: https://github.com/modelscope/swift/issues/1348
=> fix vlm deploy lora & agent

docs/source/LLM/命令行参数.md, docs/source_en/LLM/Command-line-parameters.md, examples/pytorch/llm/custom.py, swift/llm/tuner.py, swift/llm/utils/argument.py, swift/llm/utils/dataset.py, swift/llm/utils/model.py
=> Support lora regex

docs/source/LLM/命令行参数.md, docs/source_en/LLM/Command-line-parameters.md, swift/llm/infer.py, swift/llm/rlhf.py, swift/llm/sft.py, swift/llm/utils/argument.py
=> Support max memory args

swift/llm/rlhf.py, swift/llm/sft.py
=> fix max_memory

swift/llm/rlhf.py, swift/llm/sft.py
(cherry picked from commit 28e0c105c10f2a4427bba46e69cbe0244c360214)
=> Fix gpu assert calculation

swift/llm/deploy.py, swift/llm/utils/argument.py, swift/llm/utils/dataset.py
=> fix dataset_sample & deploy stop_words

docs/source/Multi-Modal/internvl最佳实践.md, docs/source_en/Multi-Modal/internvl-best-practice.md, swift/llm/utils/model.py, swift/llm/utils/template.py
- update internvl doc
- fix internvl2-4b model
=> fix internvl doc

swift/llm/utils/vllm_utils.py
FIX: https://github.com/modelscope/swift/issues/1403
=> fix vllm==0.5.1

swift/llm/export.py, swift/llm/utils/dataset.py, swift/llm/utils/model.py
=> Fix glm4v merge lora

swift/utils/__init__.py, swift/utils/torch_utils.py, swift/utils/utils.py
modify `safe_ddp_context` to support TorchAcc distributed settings, thereby resolving the issue of model downloading in a TorchAcc distributed setup.
=> [TorchAcc] fix model download when using TorchAcc distributed training

swift/llm/export.py
=> Fix ollama export

swift/ui/llm_eval/llm_eval.py, swift/ui/llm_export/llm_export.py, swift/ui/llm_infer/llm_infer.py, swift/ui/llm_train/llm_train.py
=> fix web-ui params

swift/llm/infer.py, swift/llm/rlhf.py, swift/llm/sft.py, swift/llm/utils/argument.py, swift/llm/utils/template.py, swift/utils/utils.py
=> fix hub_token

swift/llm/utils/template.py
=> fix internvl2 template

swift/llm/utils/template.py, swift/llm/utils/utils.py
=> Fix bug and make lazydataset more stable

swift/llm/utils/model.py, swift/llm/utils/template.py, swift/llm/utils/utils.py
=> Fix llava-hf

swift/llm/utils/dataset.py
=> fix read csv (float)

swift/llm/utils/dataset.py
=> fix dataset

docs/source/Multi-Modal/internvl最佳实践.md, docs/source_en/Multi-Modal/internvl-best-practice.md
=> update internvl doc

docs/source/LLM/VLLM推理加速与部署.md, docs/source/LLM/命令行参数.md, docs/source_en/LLM/Command-line-parameters.md, docs/source_en/LLM/VLLM-inference-acceleration-and-deployment.md, swift/llm/deploy.py, swift/llm/utils/argument.py, swift/llm/utils/client_utils.py
=> Support api key

swift/llm/utils/dataset.py, swift/llm/utils/media.py
=> Add two datasets

docs/source/LLM/人类偏好对齐训练文档.md, docs/source_en/LLM/Human-Preference-Alignment-Training-Documentation.md, requirements/framework.txt, swift/llm/rlhf.py, swift/llm/utils/argument.py
Update the trl dependency version to 0.9.6
=> Update trl dependency version

swift/llm/utils/argument.py, swift/tuners/base.py, swift/tuners/part.py, swift/tuners/utils.py, tests/tuners/test_swift_base.py
=> add activate and deactivate for part tuner

docs/source/LLM/Megatron训练文档.md, docs/source_en/LLM/Megatron-training.md, swift/llm/megatron/utils.py, swift/llm/utils/model.py
=> fix megatron

docs/source/Multi-Modal/人类偏好对齐训练文档.md, swift/llm/data/dataset_info.json, swift/trainers/cpo_trainer.py
=> Fix visual cpo

swift/llm/utils/template.py, swift/llm/utils/vision_utils.py
=> fix import

swift/trainers/mixin.py, swift/trainers/trainers.py
=> fix resume_only_model & zero3 & full

swift/tuners/adapter.py, swift/tuners/base.py, swift/tuners/llamapro.py, swift/tuners/lora_layers.py, swift/tuners/part.py, swift/tuners/prompt.py, swift/tuners/restuning.py, swift/tuners/scetuning/scetuning.py, swift/tuners/side.py, swift/tuners/utils.py, tests/tuners/test_scetuning.py, tests/tuners/test_swift_base.py
=> fix part tuner

swift/llm/utils/model.py
=> fix cogvlm2-video

swift/llm/utils/template.py, swift/llm/utils/vision_utils.py
=> fix vlm template

swift/llm/rlhf.py, swift/llm/sft.py, swift/utils/torch_utils.py
=> support zero3 & freeze

swift/tuners/lora_layers.py
=> fix part mix with lora

docs/source/LLM/人类偏好对齐训练文档.md, docs/source/LLM/自定义与拓展.md, docs/source_en/LLM/Customization.md, docs/source_en/LLM/Human-Preference-Alignment-Training-Documentation.md, swift/llm/utils/dataset.py, swift/trainers/kto_trainer.py
=> fix kto custom data

README.md, README_CN.md, docs/source/LLM/自定义与拓展.md, docs/source_en/LLM/Customization.md, swift/llm/data/dataset_info.json, swift/llm/utils/model.py, swift/llm/utils/preprocess.py, swift/llm/utils/template.py, swift/utils/run_utils.py
=> fix pretrain dataset

swift/llm/infer.py, swift/llm/utils/argument.py, swift/llm/utils/template.py, swift/llm/utils/vision_utils.py
=> fix deepseek-vl template

docs/source/LLM/命令行参数.md, docs/source_en/LLM/Command-line-parameters.md, swift/llm/export.py, swift/llm/utils/argument.py
=> Support exporting of llama3.1, and awq-batch-size

swift/llm/utils/template.py
=> fix tf 4.43 llava

swift/llm/utils/template.py
fix padding_side for internvl-phi3 template
=> fix internvl-phi3 batch infer

requirements/framework.txt, requirements/llm.txt, swift/llm/app_ui.py, swift/llm/deploy.py, swift/llm/utils/lmdeploy_utils.py, swift/llm/utils/vllm_utils.py
=> support lmdeploy  & app-ui

swift/llm/utils/model.py
=> fix multi node

swift/llm/tuner.py
=> fix xcomposer lora

docs/source/LLM/自定义与拓展.md, docs/source_en/LLM/Customization.md, swift/trainers/cpo_trainer.py, swift/trainers/dpo_trainer.py, swift/trainers/kto_trainer.py, swift/trainers/orpo_trainer.py
- Added data anomaly detection logic.
- Fixed internvl models' forward errors with full sft and with specified ref_model.
=> fix some bugs in dpo

swift/llm/utils/lmdeploy_utils.py
=> fix qwen-vl-merged lmdeploy

docs/source/LLM/Agent部署最佳实践.md, docs/source_en/LLM/Agent-deployment-best-practice.md, swift/llm/deploy.py
fix `tool_calls` to be list type
=> fix agent deployment

swift/llm/megatron/convert.py, tests/custom/test_megatron.py
=> Fix megatron convert

docs/source/LLM/命令行参数.md, docs/source_en/LLM/Command-line-parameters.md, swift/tuners/lora_layers.py, tests/custom/test_main.py
=> fix peft==0.11

docs/source/Multi-Modal/internvl最佳实践.md, docs/source_en/Multi-Modal/internvl-best-practice.md
=> Fix InternVL2 doc

swift/llm/export.py, swift/llm/utils/argument.py, swift/llm/utils/model.py, swift/llm/utils/utils.py
=> Fix rope scaling

swift/llm/utils/utils.py
=> fix rope scaling bug

swift/llm/utils/template.py
=> fix florence template

README.md, docs/source/LLM/LLM推理文档.md, docs/source/Multi-Modal/MLLM部署文档.md, docs/source/Multi-Modal/qwen-audio最佳实践.md, docs/source/Multi-Modal/qwen-vl最佳实践.md, docs/source_en/LLM/LLM-inference.md, docs/source_en/Multi-Modal/mutlimodal-deployment.md, docs/source_en/Multi-Modal/qwen-audio-best-practice.md, docs/source_en/Multi-Modal/qwen-vl-best-practice.md, requirements/framework.txt, swift/llm/utils/lmdeploy_utils.py, swift/llm/utils/model.py, swift/llm/utils/template.py, swift/llm/utils/vllm_utils.py, swift/utils/module_mapping.py, tests/llm/test_run.py
=> Compat transformers 4.44

swift/llm/utils/argument.py, swift/llm/utils/model.py, swift/tuners/peft.py
FIX https://github.com/modelscope/ms-swift/issues/1643
=> fix xcomposer lora_target_modules

swift/llm/utils/template.py
=> fix TypeError: 'NoneType' object is not iterable, when only have video data the image is none

swift/llm/utils/argument.py, swift/tuners/peft.py
=> fix peft patch

swift/trainers/__init__.py, swift/trainers/cpo_trainer.py, swift/trainers/dpo_trainer.py, swift/trainers/kto_trainer.py, swift/trainers/orpo_trainer.py, swift/trainers/utils.py
=> fix oom test in rlhf

swift/utils/utils.py
fix broadcast of output_dir for TorchAcc.
=> [TorchAcc] fix bcast of output_dir

swift/llm/utils/argument.py, swift/llm/utils/model.py
=> fix tp lmdeploy

swift/llm/utils/argument.py
=> fix transformers==4.33

swift/llm/utils/dataset.py
=> update aishell1 dataset

docs/source/LLM/OLLAMA导出文档.md, docs/source/LLM/index.md, docs/source/index.rst, docs/source_en/LLM/OLLaMA-Export.md, docs/source_en/LLM/index.md, docs/source_en/index.rst, swift/llm/export.py
=> Add OLLaMA doc

swift/llm/utils/template.py
=> fix infer deploy

README.md, README_CN.md
=> add paper link

docs/source/LLM/ORPO算法最佳实践.md, docs/source/Multi-Modal/人类偏好对齐训练文档.md, docs/source_en/LLM/Human-Preference-Alignment-Training-Documentation.md, docs/source_en/LLM/ORPO.md, docs/source_en/Multi-Modal/human-preference-alignment-training-documentation.md, swift/trainers/cpo_trainer.py, swift/trainers/dpo_trainer.py, swift/trainers/orpo_trainer.py, swift/trainers/utils.py
=> set default writer_batch_size argument in mllm rlhf

swift/ui/llm_eval/eval.py, swift/ui/llm_infer/llm_infer.py
=> fix video component

docs/source/LLM/人类偏好对齐训练文档.md, swift/trainers/cpo_trainer.py, swift/trainers/dpo_trainer.py, swift/trainers/orpo_trainer.py
fix error when using mllm rlhf with DDP
`AttributeError: 'DistributedDataParallel' object has no attribute 'dtype'. Did you mean: 'type'?`
=> fix model dtype in rlhf 

swift/llm/utils/template.py, swift/llm/utils/vision_utils.py
=> Fix minicpmv 2.6  & video/plain-text bug

swift/llm/utils/model.py, swift/llm/utils/template.py
=> Fix internvl2 device map

swift/llm/tuner.py, swift/llm/utils/model.py
=> Support deepseek-v2 base

swift/llm/tuner.py, swift/torchacc_utils.py
Consolidate FSDP checkpoint after saving instead of during loading.
=> [TorchAcc] consolidate FSDP ckpt after saving instead of during loading

docs/source/LLM/LLM量化与导出文档.md, docs/source_en/LLM/LLM-quantization-and-export.md, swift/llm/deploy.py, swift/llm/utils/model.py
FIX: https://github.com/modelscope/ms-swift/issues/1682
=> fix deploy stream

swift/llm/utils/preprocess.py, swift/trainers/cpo_trainer.py, swift/trainers/dpo_trainer.py, swift/trainers/orpo_trainer.py, swift/trainers/utils.py
compatibility with current modifications in template
related issue : https://github.com/modelscope/ms-swift/issues/1702
test:
- mllm: internvl for both non-streaming and streaming data
- llm : qwen2
=> Fix mllm rlhf 

swift/llm/deploy.py, swift/llm/utils/model.py, swift/llm/utils/protocol.py
=> Fix minicpm-v-v2.6 device_map='auto' & agent deploy

swift/trainers/cpo_trainer.py, swift/trainers/dpo_trainer.py, swift/trainers/orpo_trainer.py, swift/trainers/utils.py
related issue https://github.com/modelscope/ms-swift/issues/1734
=> Fix glm4v rlhf

swift/utils/metric.py
=> fix imports

swift/llm/utils/template.py
FIX: https://github.com/modelscope/ms-swift/issues/1751
=> compat with torch=1.12/1.13

swift/llm/utils/dataset.py
=> update rlaif-v hf dataset

swift/llm/utils/lmdeploy_utils.py
=> fix lmdeploy: AssertionError: failed to match chat template, please explicit set chat_template_config

swift/llm/tuner.py, swift/torchacc_utils.py
Refine the process of saving and loading checkpoints for FSDP full-parameter training. 
Initially, each rank will save its sharded checkpoint in a binary file. Subsequently, rank 0 will merge these sharded checkpoints into a complete checkpoint, formatted either as a safetensor or a binary file.
=> [TorchAcc] fix: fix saving and loading checkpoint for full sft FSDP

swift/llm/utils/argument.py, swift/llm/utils/model.py
=> fix infer dataset_test_ratio

swift/llm/deploy.py, swift/llm/utils/client_utils.py, swift/llm/utils/template.py
=> support qwen-vl & base64

swift/llm/utils/preprocess.py
=> fix history_roles

swift/llm/rlhf.py, swift/llm/utils/template.py
register preforward hook for ref model
=> fix mllm rlhf with full sft type

swift/llm/export.py, swift/llm/utils/vllm_utils.py, tests/custom/test_main.py, tests/llm/test_run.py
=> compat with vllm==0.5.5

swift/trainers/mixin.py
FIX: https://github.com/modelscope/ms-swift/issues/596
=> fix mp+ddp & resume_from_checkpoint

README.md, README_CN.md, docs/source/LLM/命令行参数.md, docs/source_en/LLM/Command-line-parameters.md, swift/llm/tuner.py, swift/llm/utils/argument.py, swift/llm/utils/utils.py, swift/trainers/trainers.py
=> Support liger

swift/llm/infer.py, swift/llm/utils/argument.py, swift/trainers/__init__.py, swift/trainers/arguments.py, swift/trainers/loss.py, swift/trainers/trainers.py, swift/utils/tb_utils.py
=> Support register loss func

swift/llm/deploy.py, swift/llm/infer.py
=> use default-lora

swift/llm/deploy.py, swift/llm/utils/model.py, swift/llm/utils/utils.py, swift/tuners/peft.py
=> fix minicpm-v 2.6 infer device_map

swift/ui/llm_eval/llm_eval.py, swift/ui/llm_export/llm_export.py, swift/ui/llm_infer/llm_infer.py, swift/ui/llm_train/llm_train.py
=> fix inject

swift/llm/utils/template.py, swift/trainers/cpo_trainer.py, swift/trainers/dpo_trainer.py, swift/trainers/orpo_trainer.py, swift/trainers/utils.py
issue https://github.com/modelscope/ms-swift/issues/1831
=> fix internlm-xcomposer rlhf

swift/llm/utils/dataset.py, swift/llm/utils/utils.py
=> Fix some datasets for streaming

swift/llm/rlhf.py, swift/llm/sft.py, swift/llm/tuner.py, swift/llm/utils/callbacks.py, swift/trainers/mixin.py
=> Fix Pissa and OLoRA

swift/llm/utils/template.py, swift/trainers/mixin.py
=> Support qwen2 vl grounding

docs/source/Multi-Modal/index.md, docs/source/index.rst, docs/source_en/Multi-Modal/index.md, docs/source_en/index.rst
=> update qwen2-vl docs

docs/source/Multi-Modal/qwen2-vl最佳实践.md, docs/source_en/Multi-Modal/qwen2-vl-best-practice.md
=> fix qwen2-vl docs

requirements/framework.txt
=> fix requirements

swift/llm/agent/utils.py, swift/llm/utils/argument.py, swift/llm/utils/dataset.py, swift/llm/utils/preprocess.py
=> Support faster data map

swift/llm/utils/utils.py, swift/ui/base.py, swift/ui/llm_train/llm_train.py, swift/ui/llm_train/lora.py, swift/ui/llm_train/model.py
=> Add train record

docs/source/LLM/命令行参数.md, docs/source_en/LLM/Command-line-parameters.md, requirements/aigc.txt, setup.py, swift/llm/sft.py, swift/llm/utils/argument.py, swift/llm/utils/lmdeploy_utils.py, swift/llm/utils/template.py, swift/llm/utils/vllm_utils.py
=> Fix num_proc

docs/source/LLM/LmDeploy推理加速与部署.md, docs/source/LLM/VLLM推理加速与部署.md, docs/source_en/LLM/LmDeploy-inference-acceleration-and-deployment.md, docs/source_en/LLM/VLLM-inference-acceleration-and-deployment.md, scripts/benchmark/deploy.py, swift/llm/utils/client_utils.py, swift/llm/utils/vision_utils.py
=> add vllm lmdeploy benchmark

swift/llm/eval.py, swift/trainers/cpo_trainer.py, swift/trainers/dpo_trainer.py, swift/trainers/kto_trainer.py, swift/trainers/orpo_trainer.py, swift/ui/llm_train/runtime.py
=> Add some warnings and fix RLHF

swift/ui/llm_export/export.py
=> support custom quantized dataset

swift/llm/ds_config/zero2.json, swift/llm/ds_config/zero2_offload.json, swift/llm/ds_config/zero3.json, swift/llm/ds_config/zero3_offload.json
=> deepspeed use cosine lr_schduler

swift/ui/llm_train/save.py
=> fix web-ui push to hub strategy

swift/llm/accelerator.py, swift/torchacc_utils.py
fix the judegement of fsdp_num
=> [TorchAcc] fix: fix the judegement of fsdp_num

swift/llm/deploy.py
=> fix swift deploy

swift/llm/deploy.py, swift/llm/utils/lmdeploy_utils.py, swift/utils/np_utils.py
=> fix lmdeploy seed

swift/llm/megatron/utils.py
=> fix file rename error in megatron when there are multi process

swift/llm/utils/vision_utils.py
FIX ISSUE: https://github.com/modelscope/ms-swift/issues/1920
=> fix qwen2-vl & video

swift/llm/utils/argument.py, swift/llm/utils/template.py, swift/llm/utils/utils.py
=> support dynamic_eos

swift/llm/rlhf.py, swift/llm/utils/utils.py, swift/trainers/__init__.py, swift/trainers/cpo_trainer.py, swift/trainers/dpo_trainer.py, swift/trainers/kto_trainer.py, swift/trainers/orpo_trainer.py
=> Add lazy_tokenize to RLHF

swift/trainers/cpo_trainer.py, swift/trainers/dpo_trainer.py, swift/trainers/kto_trainer.py, swift/trainers/orpo_trainer.py
=> Fix data info print in rlhf

swift/tuners/peft.py
=> Fix the lora hook

swift/llm/rlhf.py, swift/llm/sft.py, swift/llm/utils/argument.py, swift/llm/utils/callbacks.py, swift/llm/utils/model.py, swift/llm/utils/template.py, swift/llm/utils/utils.py, swift/trainers/arguments.py
=> Fix rlhf ref model

swift/llm/utils/client_utils.py, swift/llm/utils/model.py, swift/llm/utils/template.py
=> fix lmdeploy qwen_vl

swift/llm/eval.py
=> fix deploy eval kill

swift/llm/utils/template.py
=> fix mplug-owl3

docs/source/Multi-Modal/florence最佳实践.md, docs/source/Multi-Modal/internvl最佳实践.md, docs/source/Multi-Modal/qwen-vl最佳实践.md, docs/source/Multi-Modal/qwen2-vl最佳实践.md, docs/source_en/Multi-Modal/florence-best-pratice.md, docs/source_en/Multi-Modal/internvl-best-practice.md, docs/source_en/Multi-Modal/qwen-vl-best-practice.md, docs/source_en/Multi-Modal/qwen2-vl-best-practice.md, swift/llm/utils/template.py, tests/llm/test_template.py
=> support multi bbox grounding

swift/llm/utils/template.py
=> Fix multi coordinate grounding

swift/llm/utils/template.py
=> llama3 tool calling

docs/source/Multi-Modal/qwen2-vl最佳实践.md, docs/source_en/Multi-Modal/qwen2-vl-best-practice.md, swift/llm/utils/model.py, swift/llm/utils/template.py
=> fix qwen2vl position_ids

swift/ui/base.py, swift/ui/llm_eval/llm_eval.py, swift/ui/llm_export/llm_export.py, swift/ui/llm_infer/llm_infer.py, swift/ui/llm_train/llm_train.py
=> fix win32 quote

swift/trainers/mixin.py
=> fix rlhf zero3

swift/llm/deploy.py, swift/llm/utils/template.py
=> fix deploy openai compat

swift/llm/utils/dataset.py
FIX: https://github.com/modelscope/ms-swift/issues/2095
=> fix dataset preprocess

swift/llm/infer.py
=> fix infer device_map

swift/llm/utils/template.py, swift/llm/utils/vision_utils.py
=> fix qwen2-audio

swift/llm/sft.py
=> fix not impl bug

swift/llm/utils/model.py
=> fix model_type

swift/llm/deploy.py
=> fix deploy vllm

swift/torchacc_utils.py, swift/trainers/mixin.py
1. fix save configuration file and additional file in `_save_tpu` which is used when using TorchAcc.
2. delete sharded ckpt of TorchAcc' FSDP after ckpt consolidation.
=> [TorchAcc] fix: fix save config and additional file for swift and peft

requirements/framework.txt, swift/llm/utils/template.py
=> fix template

swift/llm/utils/argument.py, swift/trainers/rlhf_trainer/kto_trainer.py, swift/trainers/trainer_factory.py
FIX: https://github.com/modelscope/ms-swift/issues/2167
=> compat trl==0.11

swift/llm/utils/template.py
FIX https://github.com/modelscope/ms-swift/issues/2172
=> fix mplug-owl3 infer

swift/llm/utils/vision_utils.py
=> fix rescale_image

swift/llm/utils/model.py
=> Fix ovis1.6 infer

.github/workflows/publish.yaml
=> fix publish

README.md, README_CN.md, swift/llm/sft.py
=> fix sft system

swift/llm/export.py
=> fix quant blocks

swift/llm/infer.py, swift/llm/rome.py, swift/llm/utils/lmdeploy_utils.py, swift/llm/utils/vllm_utils.py
=> fix system

README.md, README_CN.md
=> update molmo readme

swift/llm/utils/model.py
=> fix molmo device_map

swift/llm/utils/preprocess.py
=> fix enable_cache

swift/llm/utils/argument.py, swift/llm/utils/model.py, swift/trainers/arguments.py, swift/trainers/mixin.py, swift/trainers/trainers.py
=> compat transformers 4.46

swift/llm/sft.py
=> fix streaming

swift/trainers/trainers.py
=> fix transformers>=4.46 loss

requirements/framework.txt, swift/trainers/loss.py, swift/trainers/trainers.py
=> fix custom loss

swift/torchacc_utils.py
fix qwen2 patch for transformers>=4.45
=> [TorchAcc] fix qwen2 for transformers>=4.45

requirements/framework.txt, swift/trainers/mixin.py, swift/trainers/rlhf_trainer/cpo_trainer.py, swift/trainers/rlhf_trainer/dpo_trainer.py, swift/trainers/rlhf_trainer/kto_trainer.py, swift/trainers/rlhf_trainer/orpo_trainer.py, swift/trainers/rlhf_trainer/reward_trainer.py
FIX: https://github.com/modelscope/ms-swift/issues/2384
FIX: https://github.com/modelscope/ms-swift/issues/2380
=> fix trl transformers==4.46 compat

swift/llm/deploy.py
=> fix deploy stream media_type

swift/llm/utils/model.py, swift/llm/utils/template.py
=> fix_mplug_owl3_cut_shape

swift/llm/utils/model.py
=> fix qwen_vl dpo

swift/llm/utils/model.py
FIX ISSUE: https://github.com/modelscope/ms-swift/issues/2412
=> Fix molmo infer

swift/llm/sft.py, swift/llm/utils/utils.py
=> Fix dataset map

swift/trainers/mixin.py
=> compat transformers==4.47

swift/llm/utils/lmdeploy_utils.py, swift/llm/utils/model.py
=> fix internvl2 lmdeploy>=0.6 deploy

swift/tuners/adapter.py, swift/tuners/llamapro.py, swift/tuners/longlora/longlora.py, swift/tuners/lora.py, swift/tuners/neftune.py, swift/tuners/part.py, swift/tuners/prompt.py, swift/tuners/restuning.py, swift/tuners/rome/rome.py, swift/tuners/scetuning/scetuning.py, swift/tuners/side.py
=> support part tuner replace_key False

swift/llm/utils/template.py, swift/version.py
=> fix qwen2vl pt infer

swift/llm/utils/utils.py
=> Fix preprocess num proc

README.md, README_CN.md
=> add doc 2.x

swift/hub/hub.py
=> fix hub param

README.md, README_CN.md, swift/llm/model/model/baai.py, swift/llm/template/template/emu3.py, tests/infer/test_main.py, tests/train/test_sft.py
support emu3 gen train and infer
=> Emu3 gen train

examples/infer/pt/all_to_all.sh
=> update memory usage of emu3-gen

docs/source/Instruction/命令行参数.md, docs/source_en/Instruction/Command-line-parameters.md, swift/llm/argument/base_args/base_args.py, swift/llm/argument/base_args/model_args.py, swift/llm/argument/infer_args.py, swift/llm/argument/train_args.py, swift/trainers/arguments.py, swift/utils/torch_utils.py
FIX: https://github.com/modelscope/ms-swift/issues/2590
=> fix use_reentrant gradient_checkpointing

swift/ui/app.py, swift/ui/llm_eval/model.py, swift/ui/llm_export/model.py, swift/ui/llm_infer/llm_infer.py, swift/ui/llm_infer/model.py, swift/ui/llm_train/model.py
=> fix app-ui

swift/llm/train/tuner.py, swift/tuners/peft.py
(cherry picked from commit a91194d97f5e2bcef1a914db27489ab79e123036)
=> fix unsloth resume training

swift/llm/export/quant.py
fix: https://github.com/modelscope/ms-swift/issues/2710
=> fix gptq group_size

swift/ui/llm_infer/runtime.py
=> Fix app-ui dropdown

swift/hub/hub.py, swift/tuners/llamapro.py, swift/tuners/peft.py
2. fix llamapro merge
3. fix adalora training
=> Fix some bugs

swift/experimental/sampling/utils.py, swift/experimental/sampling/vanilla_sampler.py, swift/plugin/orm.py
=> Fix a bug when lint code

docs/source/Customization/插件化.md, docs/source_en/Customization/Pluginization.md
=> update plugin doc

swift/llm/template/base.py
https://github.com/modelscope/ms-swift/issues/2912
=> fix replace_video2image

swift/experimental/sampling/sampling.py, swift/experimental/sampling/vanilla_sampler.py
(cherry picked from commit 1e67ebff1cfb208171b6d7888a7d06bff41e61d4)
=> Fix read file mode

swift/ui/app.py, swift/ui/llm_eval/llm_eval.py, swift/ui/llm_eval/runtime.py, swift/ui/llm_export/llm_export.py, swift/ui/llm_infer/llm_infer.py, swift/ui/llm_infer/runtime.py, swift/ui/llm_train/llm_train.py, swift/ui/llm_train/runtime.py
=> Fix web ui log

docs/source/GetStarted/Web-UI.md, docs/source/Instruction/命令行参数.md, docs/source/Instruction/支持的模型和数据集.md, docs/source_en/GetStarted/Web-UI.md, docs/source_en/Instruction/Command-line-parameters.md, docs/source_en/Instruction/Supported-models-and-datasets.md, swift/llm/argument/base_args/quant_args.py, swift/llm/argument/eval_args.py, swift/llm/eval/eval.py, swift/llm/model/constant.py, swift/llm/model/model/__init__.py, swift/llm/model/model/minimax.py, swift/llm/template/constant.py, swift/llm/template/template/__init__.py, swift/llm/template/template/minimax.py
=> Support minimax

docs/source/Instruction/命令行参数.md, docs/source_en/Instruction/Command-line-parameters.md, swift/llm/argument/base_args/template_args.py
=> sys_prompt from file

requirements/framework.txt, swift/llm/argument/rlhf_args.py, swift/llm/train/rlhf.py, swift/trainers/rlhf_arguments.py, swift/trainers/rlhf_trainer/cpo_trainer.py, swift/trainers/rlhf_trainer/dpo_trainer.py, swift/trainers/rlhf_trainer/kto_trainer.py, swift/trainers/rlhf_trainer/orpo_trainer.py, swift/trainers/rlhf_trainer/ppo_trainer.py, swift/trainers/rlhf_trainer/rlhf_mixin.py
=> compatible with trl v0.13

swift/hub/hub.py
=> fix push to hub

swift/llm/dataset/dataset/llm.py
register MathR and MathR-32B-Distill datasets which are distilled from Deepseek-R1 and DeepSeek-R1-Distill-Qwen-32B.
=> register MathR

examples/train/grpo/plugin/plugin.py, swift/plugin/orm.py
=> fix accuracy reward

swift/llm/dataset/dataset/llm.py
=> fix competition math

examples/train/rft/rft.py, scripts/benchmark/exp_utils.py, swift/llm/argument/train_args.py, swift/llm/model/model/baai.py, swift/llm/model/model/glm.py, swift/llm/model/model/llama.py, swift/llm/model/model/microsoft.py, swift/llm/model/model/minimax.py, swift/llm/model/model/qwen.py, swift/llm/model/register.py, swift/llm/sampling/base.py, swift/llm/sampling/sampling.py, swift/llm/sampling/vanilla_sampler.py, swift/llm/template/template/emu3.py, swift/llm/train/patcher.py, swift/trainers/mixin.py, swift/trainers/rlhf_trainer/grpo_trainer.py, swift/tuners/base.py, swift/tuners/utils.py, swift/ui/llm_eval/eval.py, swift/ui/llm_eval/llm_eval.py, swift/ui/llm_export/llm_export.py, swift/ui/llm_infer/llm_infer.py, swift/ui/llm_train/llm_train.py, swift/utils/__init__.py, swift/utils/env.py, swift/utils/torch_utils.py, tests/general/test_model.py
=> support cuda operations to npu

swift/llm/model/register.py, swift/llm/train/tuner.py
=> fix unsloth

swift/hub/hub.py
=> fix create_repo

swift/llm/sampling/vanilla_sampler.py
=> fix sampler reaches max_length

swift/llm/infer/infer_engine/infer_engine.py, swift/llm/sampling/utils.py
=> Fix prm in sampler

examples/train/grpo/multi_node/multi_gpu_agent.sh
=> Add links to agent grpo

swift/trainers/rlhf_trainer/grpo_trainer.py
=> fix grpo old_per_token_logps

README.md, README_CN.md, docs/source/Instruction/命令行参数.md, docs/source_en/Instruction/Command-line-parameters.md, examples/train/grpo/full_lmdeploy.sh, swift/trainers/arguments.py, swift/trainers/rlhf_trainer/grpo_trainer.py, swift/trainers/utils.py
=> Speed up GRPO

swift/llm/utils.py, swift/trainers/rlhf_trainer/grpo_trainer.py
https://github.com/modelscope/ms-swift/issues/3241
=> fix grpo npu vllm

swift/trainers/rlhf_trainer/grpo_trainer.py
=> fix grpo single card

swift/llm/infer/infer_engine/lmdeploy_engine.py
=> fix lmdeploy mllm in grpo

swift/llm/argument/rlhf_args.py, swift/trainers/rlhf_trainer/grpo_trainer.py
https://github.com/Future-House/trl/pull/7
=> fix grpo zero3

swift/plugin/orm.py, swift/trainers/rlhf_trainer/grpo_trainer.py
- [√] Bug Fix
use tokenizer to calculate output length
使用模型分词器计算长度
=> fix：fix bugs in cosine reward of GRPO

docs/source/Instruction/命令行参数.md, docs/source_en/Instruction/Command-line-parameters.md, swift/trainers/arguments.py, swift/trainers/rlhf_trainer/grpo_trainer.py
=> Support GRPO model and optimizer offload, and split loading model

swift/llm/infer/infer_engine/grpo_vllm_engine.py, swift/llm/infer/infer_engine/vllm_engine.py, swift/trainers/rlhf_trainer/grpo_trainer.py
=> Fix vllm random

swift/llm/infer/infer_engine/__init__.py, swift/llm/infer/infer_engine/utils.py, swift/llm/infer/infer_engine/vllm_engine.py, swift/trainers/rlhf_trainer/grpo_trainer.py
fix device mismatch with Qwen-VL series
=> fix GRPO device mismatch

docs/source/BestPractices/GRPO多模态训练.md
=> fix grpo multimodal doc

swift/trainers/rlhf_trainer/grpo_trainer.py
=> fix grpo temperature inconsistency

swift/llm/infer/infer_engine/utils.py, swift/trainers/rlhf_trainer/grpo_trainer.py
Fixed an issue where using GRPO with DDP (without DeepSpeed) could potentially cause a hanging problem.
=> fix grpo ddp hang

examples/train/grpo/train_72b_4gpu.sh
Line 37 repeats line 34.
Delete duplicate parameter.
=> Delete duplicate parameters in train_72b_4gpu.sh

docs/source/index.rst, docs/source_en/index.rst
=> update code doc

docs/source/BestPractices/Embedding训练.md, docs/source_en/BestPractices/Embedding.md
=> Fix docs links

docs/source/GetStarted/SWIFT安装.md, docs/source_en/GetStarted/SWIFT-installation.md
=> [Docs] Easy `.[all]` install from git

swift/llm/dataset/dataset/mllm.py, swift/llm/model/model/llm.py, swift/llm/template/base.py, swift/plugin/loss.py
=> Gather infonce loss and support hard negative samples

swift/trainers/rlhf_trainer/grpo_trainer.py
=> fix grpo mllm split modules

swift/trainers/rlhf_trainer/grpo_trainer.py
Fix GRPO with LoRA for the Embedding Layer
=> grpo embedding layer lora

docs/source/BestPractices/Embedding训练.md, docs/source_en/BestPractices/Embedding.md, swift/llm/dataset/dataset/mllm.py, swift/llm/model/constant.py, swift/llm/model/model/bert.py, swift/llm/model/model/llm.py, swift/llm/model/model/mllm.py, swift/llm/model/patcher.py, swift/llm/model/register.py, swift/llm/model/utils.py, swift/plugin/loss.py
=> Support all models' embedding and mask fake negative

swift/llm/infer/infer_engine/grpo_vllm_engine.py, swift/llm/infer/infer_engine/vllm_engine.py, swift/trainers/rlhf_trainer/grpo_trainer.py
=> skip grpo first wake up

swift/trainers/rlhf_trainer/grpo_trainer.py
https://github.com/modelscope/ms-swift/issues/3567
=> move grpovllmengine import

swift/trainers/rlhf_trainer/grpo_trainer.py
https://github.com/modelscope/ms-swift/issues/3561
Fix a bug where rollout data during training is incorrectly placed in the eval_queue using async_generate.
=> [grpo] Fix Incorrect Placement of Data in eval_queue During async_generate

swift/llm/infer/infer_engine/utils.py
=> Fix lmdeploy 0.7.3

docs/source/Instruction/支持的模型和数据集.md, docs/source_en/Instruction/Supported-models-and-datasets.md, swift/llm/model/constant.py, swift/llm/model/model/mistral.py, swift/llm/model/model_arch.py, swift/llm/template/constant.py, swift/llm/template/template/__init__.py, swift/llm/template/template/llm.py, swift/llm/template/template/mistral.py, tests/test_align/test_template/test_vision.py
=> support Mistral3.1-2503

swift/llm/infer/infer_engine/utils.py
https://github.com/modelscope/ms-swift/issues/3594
=> fix grpo npu context

docs/source/Instruction/GRPO.md, swift/llm/argument/rlhf_args.py, swift/trainers/rlhf_trainer/grpo_trainer.py
=> update grpo warning

swift/trainers/rlhf_trainer/grpo_trainer.py
fix a bug in the reward model's forward pass under Zero3
=> fix grpo rm zero3

swift/llm/argument/rlhf_args.py
=> fix grpo warning

swift/trainers/rlhf_trainer/grpo_trainer.py
reset prefix cache after vllm model weight update
=> grpo reset prefix cache

swift/llm/argument/train_args.py, swift/llm/template/template/deepseek.py, swift/llm/template/template/gemma.py, swift/llm/template/template/glm.py, swift/llm/template/template/internvl.py, swift/llm/template/template/llava.py, swift/llm/template/template/microsoft.py, swift/llm/template/template/minicpm.py, swift/llm/template/template/mistral.py, swift/llm/template/template/molmo.py, swift/llm/template/template/mplug.py, swift/llm/template/template/stepfun.py, swift/llm/train/sft.py, swift/trainers/rlhf_arguments.py
https://github.com/modelscope/ms-swift/pull/3649
=> Fix template torch_dtype

swift/trainers/rlhf_trainer/grpo_trainer.py
Set max_completion_lens to the total length of multi-turn generation.
=> set grpo multi turn max tokens

swift/trainers/rlhf_trainer/grpo_trainer.py
=> fix grpo rank

examples/train/grpo/lora_qwenvl72b.sh, swift/trainers/rlhf_trainer/grpo_trainer.py
=> Grpo vl72b script

swift/llm/train/tuner.py, tests/tuners/test_peft.py
=> fix adalora

swift/llm/template/template/qwen.py, tests/test_align/test_template/test_video.py
https://github.com/modelscope/ms-swift/issues/3715
=> fix qwen2_5 omni

swift/plugin/orm.py
https://github.com/huggingface/open-r1/pull/566
=> fix math accuracy

swift/llm/argument/base_args/template_args.py, swift/llm/argument/rlhf_args.py, swift/llm/template/base.py, swift/trainers/rlhf_arguments.py
=> fix grpo zero3 inflight params

swift/llm/model/model/telechat.py
https://github.com/modelscope/ms-swift/issues/3749
https://github.com/modelscope/ms-swift/issues/3519
=> fix telechat 

swift/trainers/rlhf_trainer/grpo_trainer.py
https://github.com/modelscope/ms-swift/issues/3811
=> feat: grpo async generate thread-safe queue production

swift/trainers/rlhf_trainer/grpo_trainer.py
=> update grpo type annotations

swift/trainers/rlhf_trainer/grpo_trainer.py
=> fix grpo multi turn tp

examples/train/rft/rft.py, swift/llm/sampling/utils.py, swift/llm/sampling/vanilla_sampler.py, swift/plugin/orm.py
=> Fix sampling and rft

swift/llm/train/tuner.py
The issue was introduced in this PR: https://github.com/modelscope/ms-swift/pull/3777
=> fix multimodal target_modules

swift/trainers/rlhf_arguments.py, swift/trainers/rlhf_trainer/grpo_trainer.py
https://github.com/modelscope/ms-swift/issues/3863
=> fix grpo save checkpoint

docs/source/Instruction/支持的模型和数据集.md, docs/source_en/Instruction/Supported-models-and-datasets.md, swift/llm/model/constant.py, swift/llm/model/model/glm.py, swift/llm/template/constant.py, swift/llm/template/template/glm.py, tests/test_align/test_template/test_llm.py
=> support glm4-z1

swift/trainers/rlhf_trainer/grpo_trainer.py
https://github.com/modelscope/ms-swift/issues/3894
=> fix typealias to be compatible with Python 3.9

swift/llm/argument/rlhf_args.py
https://github.com/modelscope/ms-swift/issues/3916
=> add rm center_rewards_coefficient argument

swift/cli/sft.py, swift/llm/model/register.py
=> Update unsloth compatibility

swift/llm/utils.py
=> Fix merge sentence transformers

swift/llm/model/model/llm.py, swift/llm/utils.py, swift/trainers/mixin.py, swift/utils/__init__.py, swift/utils/utils.py, tests/utils/test_file_utils.py
=> Fix gte training and compatible with ds3

swift/llm/infer/rollout.py
=> fix rollout

examples/train/long_text/sequence_parallel_dpo.sh
=> Add sp script

swift/trainers/callback.py, swift/trainers/mixin.py, swift/trainers/sequence_parallel/base.py, swift/trainers/sequence_parallel/ulysses.py, swift/trainers/sequence_parallel/xtuner.py
=> Support ulysses streaming

swift/llm/argument/rlhf_args.py, swift/llm/train/rlhf.py
=> fix ppo init model

swift/llm/train/rlhf.py
=> fix ppo reward model

swift/trainers/rlhf_trainer/grpo_trainer.py
1. set request_config.seed consistent within TP group and different across TP groups
2. fix loss_scale in template_context
=> [grpo] fix colocate + tp

swift/llm/template/base.py, swift/trainers/rlhf_trainer/grpo_trainer.py
1. fixes the bug where the system prompt from Trainer.template was not passed to vLLMEngine in external mode.
2. polish log_completions to apply chat template to model prompt 
main branch:
The user needs to manually set the Cell expression to obtain the prompt because the provided "prompt" is a list[dict].
this pr:
The chat template is applied to the model prompt, converting the dict to a str.
=> [grpo] set system in inputs

swift/llm/train/rlhf.py
=> fix get reward model 

docs/source/Instruction/评测.md, docs/source_en/Instruction/Evaluation.md, swift/llm/argument/eval_args.py
=> fix eval extral args

docs/source/Instruction/GRPO.md, requirements/framework.txt, swift/trainers/rlhf_trainer/dpo_trainer.py, swift/trainers/rlhf_trainer/rlhf_mixin.py
=> [rlhf] prepare_model for ref_model & reduce peak memory in dpo

docs/source/Instruction/GRPO.md, docs/source/Instruction/命令行参数.md, docs/source_en/Instruction/Command-line-parameters.md, docs/source_en/Instruction/GRPO.md, swift/trainers/arguments.py, swift/trainers/rlhf_trainer/grpo_trainer.py
=> [grpo] support synchronizing ref model

swift/llm/infer/infer_engine/grpo_vllm_engine.py, swift/llm/infer/infer_engine/vllm_engine.py, swift/llm/infer/rollout.py
=> [grpo] set v1 engine as default in external rollout

examples/train/multimodal/rlhf/dpo/full.sh, examples/train/multimodal/rlhf/dpo/lora.sh, examples/train/rlhf/ppo/full.sh, examples/train/rlhf/ppo/lora.sh, swift/trainers/mixin.py, swift/trainers/rlhf_trainer/ppo_trainer.py
https://github.com/huggingface/trl/issues/2122
=> fix ppo zero3

swift/llm/data_loader.py, swift/trainers/mixin.py, swift/trainers/rlhf_trainer/dpo_trainer.py, swift/trainers/sequence_parallel/ulysses.py
=> fix ulysses eval

swift/trainers/sequence_parallel/ulysses.py
=> Fix ulysses pending

docs/source/Instruction/GRPO.md, docs/source_en/Instruction/GRPO.md, examples/train/grpo/external/README.md, examples/train/grpo/external/grpo_32b_full.sh, examples/train/grpo/external/grpo_7b.sh, examples/train/grpo/internal/vllm_vl7b.sh, swift/llm/infer/infer_engine/grpo_vllm_engine.py, swift/llm/infer/infer_engine/vllm_engine.py, swift/llm/infer/rollout.py, swift/trainers/rlhf_trainer/grpo_trainer.py
=> [grpo] support dp in external mode

docs/source/BestPractices/GRPO代码训练.md, docs/source/GetStarted/Web-UI.md, docs/source/Instruction/GRPO.md, docs/source/Instruction/Megatron-SWIFT训练.md, docs/source_en/BestPractices/GRPO-Code-Training.md, docs/source_en/GetStarted/Web-UI.md, docs/source_en/Instruction/GRPO.md, docs/source_en/Instruction/Megatron-SWIFT-Training.md, swift/megatron/argument/megatron_args.py, swift/megatron/model/register.py
https://github.com/modelscope/ms-swift/pull/4240
=> update link & update extra_megatron_kwargs

docs/source/BestPractices/Embedding训练.md, docs/source_en/BestPractices/Embedding.md
=> fix emb docs

docs/source/Instruction/GRPO.md, docs/source/Instruction/命令行参数.md, docs/source_en/Instruction/Command-line-parameters.md, docs/source_en/Instruction/GRPO.md, swift/trainers/arguments.py, swift/trainers/rlhf_trainer/vllm_client.py
https://github.com/huggingface/trl/pull/3324
=> [grpo] support vllm_server_base_url for vLLMClient

swift/trainers/rlhf_trainer/grpo_trainer.py
fix colocate mode hang issue when using lora
=> [grpo] fix hang in colocate lora settings

requirements/eval.txt
=> [eval] fix eval dependence

swift/llm/argument/rlhf_args.py
=> [grpo] update grpo check

swift/llm/dataset/dataset/llm.py
=> [Dataset]add stsb positive subset

docs/source/BestPractices/Embedding训练.md, docs/source_en/BestPractices/Embedding.md, examples/train/embedding/train_emb.sh
=> fix emb script and docs

docs/source/Instruction/GRPO.md, docs/source/Instruction/命令行参数.md, docs/source_en/Instruction/Command-line-parameters.md, docs/source_en/Instruction/GRPO.md
move `mvoe_model_batches` to common argument after https://github.com/modelscope/ms-swift/pull/4453
=> [grpo] update doc about move_model_batches

swift/trainers/mixin.py
=> fix qwen3 embedding saving

swift/trainers/rlhf_trainer/grpo_trainer.py
https://github.com/modelscope/ms-swift/issues/4557
=> [grpo] fix the pickle data collator

swift/ui/llm_train/llm_train.py
Fix merged model for UI training.
=> Fix UI llm_train

docs/source/BestPractices/Embedding训练.md, docs/source/BestPractices/GRPO完整流程.md, docs/source/Instruction/GRPO.md, docs/source/conf.py, docs/source_en/BestPractices/Embedding.md, docs/source_en/BestPractices/GRPO.md, docs/source_en/Instruction/GRPO.md, docs/source_en/conf.py
support LaTeX rendering in readthedocs
main branch:
this pr:
=> [doc] LaTeX rendering

docs/source/Instruction/GRPO/DeveloperGuide/多轮训练.md, docs/source/Instruction/GRPO/GetStarted/GRPO.md, docs/source_en/Instruction/GRPO/DeveloperGuide/multi_turn.md, docs/source_en/Instruction/GRPO/GetStarted/GRPO.md
=> [doc] fix image link

docs/source/Instruction/GRPO/GetStarted/GRPO.md, docs/source_en/Instruction/GRPO/GetStarted/GRPO.md
=> [doc] fix doc

docs/source/Instruction/GRPO/GetStarted/GRPO.md, docs/source_en/Instruction/GRPO/GetStarted/GRPO.md, swift/llm/infer/rollout.py
=> [rollout] fix dp args

README.md, README_CN.md, docs/source/Instruction/GRPO/DeveloperGuide/多轮训练.md, docs/source/Instruction/命令行参数.md, docs/source_en/Instruction/Command-line-parameters.md, docs/source_en/Instruction/GRPO/DeveloperGuide/multi_turn.md
=> [docs] fix grpo docs

docs/source/Instruction/GRPO/DeveloperGuide/奖励函数.md, docs/source_en/Instruction/GRPO/DeveloperGuide/reward_function.md, examples/train/grpo/plugin/plugin.py, swift/trainers/rlhf_trainer/grpo_trainer.py
=> [grpo] pass trainer state to reward funcs

docs/source/Customization/自定义数据集.md, docs/source/Instruction/人类对齐.md, docs/source_en/Customization/Custom-dataset.md, docs/source_en/Instruction/RLHF.md, swift/llm/argument/rlhf_args.py, swift/llm/dataset/preprocessor/core.py, swift/llm/template/base.py, swift/llm/template/template_inputs.py, swift/llm/train/rlhf.py, swift/trainers/rlhf_trainer/reward_trainer.py
=> [RM] support margin & update doc

.github/workflows/close_tale_issue.yaml
=> [GITHUB WORKFLOW]add close stale issues workflow

swift/llm/infer/infer_engine/grpo_vllm_engine.py
https://github.com/modelscope/ms-swift/issues/4824
=> [rollout] fix request from dict

docs/source/Instruction/支持的模型和数据集.md, docs/source_en/Instruction/Supported-models-and-datasets.md, swift/llm/model/constant.py, swift/llm/model/model/mllm.py, swift/llm/model/model_arch.py, swift/llm/template/constant.py, swift/llm/template/template/__init__.py, swift/llm/template/template/kwai.py, tests/test_align/test_template/test_video.py, tests/test_align/test_template/test_vision.py
=> Support Kwai-Keye/Keye-VL-8B-Preview

swift/llm/argument/rlhf_args.py
=> [grpo] fix server arg check

swift/trainers/sequence_parallel/utils.py
=> fix loss_scale sp

swift/trainers/sequence_parallel/ring_attention.py, swift/trainers/sequence_parallel/ulysses.py, swift/trainers/sequence_parallel/utils.py
=> optimize imports

swift/llm/template/template/kwai.py
=> Fix: Correct training hang for Keye-VL on DeepSpeed with mixed data

swift/llm/template/template/llm.py
=> Fix the template suffix of qwen3 embedding

swift/trainers/rlhf_trainer/utils.py
fix a bug introduced in https://github.com/modelscope/ms-swift/pull/4907
=> [bugfix] fix profiling patch

examples/train/grpo/plugin/plugin.py
Modify format reward to support a wider range of output formats. See [#238](https://github.com/huggingface/open-r1/pull/238)
=> fix format reward

docs/source/Customization/自定义数据集.md, docs/source_en/Customization/Custom-dataset.md, swift/llm/dataset/preprocessor/core.py, swift/llm/template/base.py, swift/llm/template/template_inputs.py, tests/train/test_grpo.py, tests/train/test_sft.py
Support passing `rejected_images` as image inputs for rejected responses in the multimodal RLHF training method.
https://github.com/modelscope/ms-swift/issues/4940
=> [rlhf] support rejected images

swift/trainers/rlhf_trainer/grpo_trainer.py
=> [grpo] fix gym check

examples/train/multi-node/deepspeed/train.sh
=> [Fix] deepspeed example shell command path for host.txt

swift/llm/infer/infer_engine/utils.py
https://github.com/modelscope/ms-swift/issues/5010
fix issue when parsing vllm version during version check
=> fix vllm version parse

swift/trainers/sequence_parallel/ulysses.py
=> Fix sp+tf4.53

docs/source/Instruction/GRPO/DeveloperGuide/GYM环境训练.md, docs/source_en/Instruction/GRPO/DeveloperGuide/gym_env.md, examples/train/grpo/external/vllm_gym.sh
=> [doc] fix gym example and doc

swift/llm/argument/base_args/base_args.py, swift/llm/model/register.py, swift/trainers/arguments.py, swift/trainers/trainers.py
=> Support ddp of unsloth

docs/source/Instruction/命令行参数.md, docs/source_en/Instruction/Command-line-parameters.md, examples/train/long_text/ring_attention/sequence_parallel.sh, examples/train/long_text/ring_attention/sequence_parallel_256k.sh, examples/train/long_text/ulysses/sequence_parallel.sh, examples/train/long_text/ulysses/sequence_parallel_512k.sh, swift/llm/argument/base_args/base_args.py, swift/llm/argument/base_args/model_args.py, swift/llm/model/register.py, swift/llm/model/utils.py
=> Fix rope-scaling

swift/trainers/sequence_parallel/utils.py
https://github.com/modelscope/ms-swift/issues/5119
=> [bugfix] fix grpo SP without padding_free error

requirements/framework.txt, tests/run.py
=> fix CVE-2025-50460: https://github.com/Anchor0221/CVE-2025-50460

swift/llm/argument/rlhf_args.py
=> [grpo] set default gas to 1

swift/llm/infer/infer_engine/grpo_vllm_engine.py, swift/llm/infer/protocol.py, swift/llm/template/template_inputs.py
fix a bug introduced in https://github.com/modelscope/ms-swift/pull/5082
`result_choice.process_images()` is not implemented
=> [bugfix] fix process_images in multi turn rollout

docs/source/Instruction/命令行参数.md, docs/source_en/Instruction/Command-line-parameters.md, swift/llm/train/sft.py, swift/trainers/arguments.py, swift/trainers/mixin.py
=> support flash checkpoint by integrated with DLRover

examples/train/embedding/train_emb.sh
=> Fix emb script

swift/tuners/lora_layers.py
=> fix peft 0.17 ci

swift/llm/template/template/kwai.py, swift/llm/template/template/qwen.py, swift/llm/train/sft.py
unused or unrecognized kwargs images
=> remove warning: unused or unrecognized kwargs images

docs/source/Instruction/Megatron-SWIFT训练.md, docs/source_en/Instruction/Megatron-SWIFT-Training.md, swift/megatron/argument/megatron_args.py, swift/megatron/trainers/trainer.py, swift/plugin/loss.py
https://github.com/modelscope/ms-swift/pull/5355
=> [megatron] Support megatron dft

swift/llm/infer/infer_engine/grpo_vllm_engine.py, swift/plugin/multi_turn.py
=> [bugfix] fix import issues

swift/llm/infer/infer_engine/vllm_engine.py
=> fix vllm embedding

swift/llm/template/template/utils.py
=> fix think template prepend nothink_prefix

swift/llm/template/template/qwen.py
Adapt the Ovis-2.5 template to vLLM
=> [vllm] support ovis2.5

swift/trainers/rlhf_trainer/grpo_trainer.py
=> [bugfix] fix grpo log image check

swift/trainers/rlhf_trainer/ppo_trainer.py
fix save_checkpint bug in trl PPOTrainer
```
if self.control.should_save:
self._save_checkpoint(model, trial=None, metrics=None)
```
=> [ppo] fix save checkpoint

swift/llm/template/base.py
=> [bugfix] set default padding side to left for generative reranker

swift/llm/template/template/qwen.py, swift/megatron/model/mm_gpt/qwen.py
https://github.com/modelscope/ms-swift/issues/5796
=> [bugfix] fix ovis2_5

docs/source/Instruction/命令行参数.md, docs/source_en/Instruction/Command-line-parameters.md
add `mcore_adapters` parameter to export arguments
-
=> docs(Instruction): add mcore_adapters parameter to export arguments

docs/source/Instruction/评测.md, docs/source_en/Instruction/Evaluation.md, swift/llm/eval/utils.py, swift/trainers/mixin.py
=> fix evalscope config dump error

swift/llm/infer/rollout.py, swift/trainers/rlhf_trainer/grpo_trainer.py
https://github.com/modelscope/ms-swift/issues/6004
https://github.com/modelscope/ms-swift/issues/6005
=> [grpo] fix gspo & rollout template register
